# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
appVersion: 1.18.0
description: A Helm Chart for TIBCO Platform Control Plane Permissions Engine
name: pengine
version: 1.18.0
