
---------------------------------------------------------
-- Database (monitoringdb) schema based on finops 1.0.0
---------------------------------------------------------

--
-- 1. Name: DATAPLANES
--

CREATE TABLE IF NOT EXISTS DATAPLANES (
  DATAPLANE_ID VARCHAR(255),
  SUBSCRIPTION_ID VARCHAR(255),
  ACTIVE BOOLEAN,
  TIBTUNNEL_STATUS BOOLEAN,
  STATUS VARCHAR(16),
  LAST_UPDATED INT,
  LATEST_UPDATE TEXT,
  MESSAGE TEXT,
  REGISTERED_REGION TEXT,
  RUNNING_REGION TEXT,
  HOST_CLOUD_TYPE TEXT,
  PRIMARY KEY (DATAPLANE_ID)
);

--
-- 2. Name: CAPABILITY_INSTANCES
--

CREATE TABLE IF NOT EXISTS CAPABILITY_INSTANCES (
  INSTANCE_ID VARCHAR(255),
  DATAPLANE_ID VARCHAR(255),
  CAPABILITY_ID VARCHAR(255),
  CAPABILITY_VERSION int[],
  CAPABILITY_TYPE VARCHAR(255),
  ACTIVE BOOLEAN,
  STATUS VARCHAR(16),
  LAST_UPDATED INT,
  MESSAGE TEXT,
  PRIMARY KEY (INSTANCE_ID),
  CONSTRAINT FK_DATAPLANE
  FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);


--
-- 3. Name: SERVICES
--

CREATE TABLE IF NOT EXISTS SERVICES (
  NAME VARCHAR(50),
  INSTANCE_ID VARCHAR(255),
  STATUS VARCHAR(16),
  LAST_UPDATED INT,
  MESSAGE TEXT,
  PRIMARY KEY (NAME,INSTANCE_ID),
  CONSTRAINT FK_INSTANCE_ID
  FOREIGN KEY (INSTANCE_ID) REFERENCES CAPABILITY_INSTANCES(INSTANCE_ID)
);

--
-- 4. Name: CAPABILITY_METADATA
--

CREATE TABLE IF NOT EXISTS CAPABILITY_METADATA (
  CAPABILITY_ID VARCHAR(50),
  VERSION int[] NOT NULL,
  CAPABILITY_TYPE VARCHAR(50),
  DEPENDS_ON jsonb,
  SERVICES TEXT[],
  
  CONSTRAINT CAPABILITY_METADATA_PKEY PRIMARY KEY (CAPABILITY_ID, VERSION,CAPABILITY_TYPE)
);

--
-- 5. Name: DATAPLANE_METRICS
--

CREATE TABLE IF NOT EXISTS HOMEPAGE_METRICS (
  SUBSCRIPTION_ID VARCHAR(50),
  CAPABILITY_ID VARCHAR(50),
  METRIC_ID VARCHAR(50),
  REGION VARCHAR(50),
  HOST_CLOUD_TYPE VARCHAR(50),
  HISTORY jsonb,
  LAST_UPDATED INT,
  
  CONSTRAINT HOMEPAGE_METRICS_PKEY PRIMARY KEY (SUBSCRIPTION_ID, METRIC_ID,CAPABILITY_ID,REGION,HOST_CLOUD_TYPE)
);

--
-- 6. Name: DOMAINS
--

CREATE TABLE IF NOT EXISTS DOMAINS (
  DOMAIN_NAME VARCHAR(255),
  DATAPLANE_ID VARCHAR(255),
  ACTIVE BOOLEAN,
  STATUS VARCHAR(16),
  LAST_UPDATED INT,
  MESSAGE TEXT,
  PRIMARY KEY (DOMAIN_NAME, DATAPLANE_ID),
  CONSTRAINT FK_DATAPLANE
  FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);

--
-- 7. Name: SCHEMA_VERSION
--

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
	ID SERIAL PRIMARY KEY, 
	VERSION INTEGER NOT NULL,
	
	CONSTRAINT UNIQUE_CONSTRAINT UNIQUE (VERSION)
);

INSERT INTO SCHEMA_VERSION(VERSION) VALUES (1) ON CONFLICT DO NOTHING;