---------------------------------------------------------
-- Database (monitoringdb) schema based on finops 1.1.0
---------------------------------------------------------
--
-- 1. Name: TIBTUNNEL_STATUS
--

CREATE TABLE IF NOT EXISTS TIBTUNNEL_STATUS (
  DATAPLANE_ID VARCHAR(255),
  TUNNEL_STATUS BOOLEAN,  
  LAST_UPDATED INT DEFAULT date_part('epoch'::text, now()),
  PRIMARY KEY (DATAPLANE_ID),
  CONSTRAINT FK_DATAPLANE
  FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);

-- TRIGGER_SET_LAST_UPDATED_TIME() to make last_updated column update automatically
DROP FUNCTION IF EXISTS TRIGGER_SET_LAST_UPDATED_TIME() CASCADE;
CREATE FUNCTION TRIGGER_SET_LAST_UPDATED_TIME()
RETURNS TRIGGER 
LANGUAGE PLPGSQL
AS $function$
BEGIN
 	NEW.LAST_UPDATED= (select cast(EXTRACT(EPOCH FROM NOW()) as bigint));
	RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS SET_LAST_UPDATED_TIME ON TIBTUNNEL_STATUS;
CREATE TRIGGER SET_LAST_UPDATED_TIME BEFORE UPDATE OF TUNNEL_STATUS ON TIBTUNNEL_STATUS FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_LAST_UPDATED_TIME();

DROP FUNCTION IF EXISTS PROC_INSERT_TIBTUNNEL_STATUS() CASCADE;
CREATE FUNCTION PROC_INSERT_TIBTUNNEL_STATUS()
RETURNS TRIGGER 
LANGUAGE PLPGSQL
AS $function$
BEGIN
  INSERT INTO TIBTUNNEL_STATUS (DATAPLANE_ID, TUNNEL_STATUS) VALUES (NEW.DATAPLANE_ID, 'false') ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS INSERT_TIBTUNNEL_STATUS ON DATAPLANES;
CREATE TRIGGER INSERT_TIBTUNNEL_STATUS AFTER INSERT ON DATAPLANES FOR EACH ROW EXECUTE PROCEDURE PROC_INSERT_TIBTUNNEL_STATUS();


-- EXPORT PAST KNOWN TIBTUNNEL_STATUS TO NEW TABLE
INSERT INTO TIBTUNNEL_STATUS (DATAPLANE_ID) 
(SELECT DATAPLANES.DATAPLANE_ID FROM DATAPLANES
WHERE DATAPLANES.ACTIVE='true') ON CONFLICT DO NOTHING;

-- DROP TIBTUNNEL_STATUS COLUMN FROM DATAPLANES
ALTER TABLE DATAPLANES DROP COLUMN IF EXISTS TIBTUNNEL_STATUS;

-------------------------------------------------------------------------
-- Database (monitoringdb) FINOPS METRICS schema based on finops 1.1.0
-------------------------------------------------------------------------

--
-- 1. Name: RUNNING_APP_INSTANCES
--

CREATE TABLE IF NOT EXISTS RUNNING_APP_INSTANCES (
  DATAPLANE_ID VARCHAR,
  SUBSCRIPTION_ID VARCHAR,
  APP_ID VARCHAR,
  CAPABILITY_ID VARCHAR,
  CONNECTORS VARCHAR,
  TAGS VARCHAR,
  RAI NUMERIC,
  DATED DATE,
  PRIMARY KEY (DATAPLANE_ID,APP_ID,DATED),
  CONSTRAINT fk_dp_id FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);

--
-- 2. Name: CLIENT_CONNECTIONS
--

CREATE TABLE IF NOT EXISTS CLIENT_CONNECTIONS(
  DATAPLANE_ID VARCHAR,
  SUBSCRIPTION_ID VARCHAR,
  CAPABILITY_ID VARCHAR,
  CONNECTIONS NUMERIC,
  DATED DATE,
  PRIMARY KEY (DATAPLANE_ID,CAPABILITY_ID,DATED),
  CONSTRAINT fk_dp_id FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);

--
-- 3. Name: ADAPTERS
--

CREATE TABLE IF NOT EXISTS ADAPTERS(
  DATAPLANE_ID VARCHAR,
  SUBSCRIPTION_ID VARCHAR,
  CAPABILITY_ID VARCHAR,
  ADAPTERS VARCHAR,
  DATED DATE,
  PRIMARY KEY (DATAPLANE_ID,CAPABILITY_ID,DATED),
  CONSTRAINT fk_dp_id FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);

--
-- 4. Name: PROCESSORS
--

CREATE TABLE IF NOT EXISTS PROCESSORS(
  DATAPLANE_ID VARCHAR,
  SUBSCRIPTION_ID VARCHAR,
  CAPABILITY_ID VARCHAR,
  AGENT_IP VARCHAR,
  PROCESSORS NUMERIC,
  DATED DATE,
  PRIMARY KEY (DATAPLANE_ID,AGENT_IP,CAPABILITY_ID,DATED),
  CONSTRAINT fk_dp_id FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);

-- UPGRADE VERSION
UPDATE SCHEMA_VERSION SET VERSION = 2;
