---------------------------------------------------------
-- Database (monitoringdb) schema based on finops 1.3.0
---------------------------------------------------------
-- 
-- 1. Swap CLIENT_CONNECTIONS for CLIENT_CONNECTIONS_V2
--     now with INSTANCE_ID!
--

CREATE TABLE IF NOT EXISTS CLIENT_CONNECTIONS_V2(
  DATAPLANE_ID VARCHAR,
  SUBSCRIPTION_ID VARCHAR,
  CAPABILITY_ID VARCHAR,
  INSTANCE_ID VARCHAR,
  CONNECTIONS NUMERIC,
  DATED DATE,
  PRIMARY KEY (DATAPLANE_ID,CAPABILITY_ID,INSTANCE_ID,DATED),
  CONSTRAINT fk_dp_id FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);
DROP TABLE IF EXISTS CLIENT_CONNECTIONS CASCADE;

CREATE TABLE IF NOT EXISTS RESOURCES (
  RESOURCE_INSTANCE_ID VARCHAR(255),
  DATAPLANE_ID VARCHAR(255),
  RESOURCE_TYPE VARCHAR(255),
  ACTIVE BOOLEAN,
  STATUS VARCHAR(16),
  LAST_UPDATED INT,
  MESSAGE TEXT,
  PRIMARY KEY (RESOURCE_INSTANCE_ID),
  CONSTRAINT FK_DATAPLANE
  FOREIGN KEY (DATAPLANE_ID) REFERENCES DATAPLANES(DATAPLANE_ID)
);
DROP TABLE IF EXISTS DOMAINS CASCADE;
-- UPGRADE VERSION
UPDATE SCHEMA_VERSION SET VERSION = 3;
