{{- if and .Values.lite.enabled .Values.plugins.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mcp-gateway-plugins
  labels:
    {{- include "tp-mcp-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.plugins.config | nindent 4 }}
{{- end }}
