# Copyright © 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

global:
  tibco:
    idleSessionTimeoutInSeconds: "14400"
    containerRegistry:
      url: ""
      username: ""
      password: ""
      repository: ""
      imagePullSecretName: ""
      customCertSecret: ""
    controlPlaneInstanceId: ""
    enableResourceConstraints: true
    useSingleNamespace: true
    serviceAccount: ""
    # The fluentbit configuration section.
    # It specifies that the fluentbit should not run as a non-root user and the user ID should be 0 (root).
    # Privilege escalation is not allowed for security reasons.
    # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
    # GitHub issue: https://github.com/fluent/fluent-bit/issues/872#issuecomment-827763207, https://github.com/kyma-project/kyma/pull/11657/files
    logging:
      fluentbit:
        enabled: true
        image:
          name: "common-fluentbit"
          registry: ""
          repo: ""
          tag: 5.0.9
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 150Mi
    proxy:
      httpProxy: ""
      httpsProxy: ""
      noProxy: ""
  external:
    storage:
      pvcName: "control-plane-pvc"
    environment: ""

# Sub charts
flogo-recipes:
  enabled: true
  flogoprovisioner:
    image:
      tag: "1027-platform-1.19.0"
    config:
      APP_INIT_IMAGE_TAG: "81"
      APP_HELMCHART_VERSION: "1.19.13"
      INFRA_CP_PROXY_IMAGE_TAG: "348"
      APP_INIT_CPU_LIMIT: "200m"
      APP_INIT_MEMORY_LIMIT: "400Mi"
      APP_INIT_CPU_REQUEST: "100m"
      APP_INIT_MEMORY_REQUEST: "100Mi"
      FLOGO_APP_BASE_IMAGE_TAG: "2.26.6-b584"
    resources:
      requests:
        cpu: "2"
        memory: 2Gi
      limits:
        cpu: "4"
        memory: 4Gi

flogo-webserver:
  enabled: true

flogo-utilities:
  enabled: true
