# Copyright © 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

global:
  tibco:
    containerRegistry:
      url: ""
      username: ""
      password: ""
      repository: ""
      imagePullSecretName: ""
      customCertSecret: ""
    controlPlaneInstanceId: ""
    enableResourceConstraints: true
    useSingleNamespace: true
    serviceAccount: ""
    proxy:
      http: ""
      https: ""
      noproxy: ""
  external:
    storage:
      pvcName: "control-plane-pvc"

# Sub charts
fileserver:
  enabled: true
