# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
appVersion: 1.17.0
dependencies:
- condition: web-server.enabled
  name: web-server
  version: 1.17.*
- condition: orchestrator.enabled
  name: orchestrator
  version: 1.17.*
- condition: user-subscriptions.enabled
  name: user-subscriptions
  version: 1.17.*
- condition: cronjobs.enabled
  name: cronjobs
  version: 1.17.*
- condition: identity-management.enabled
  name: identity-management
  version: 1.17.*
- condition: identity-provider.enabled
  name: identity-provider
  version: 1.17.*
- condition: pengine.enabled
  name: pengine
  version: 1.17.*
description: A Helm chart for -- tp-cp-core
name: tp-cp-core
version: 1.17.0
