#
# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
appVersion: "5.2.0-3"
description: Tibco ActiveSpaces distributed data grid
home: https://www.tibco.com/products/tibco-activespaces
keywords:
- msg-activespaces
name: msg-activespaces-tp
type: application
version: "1.19.23"
# version: "1.19.18"
