-- Database schema changes for 1.11.0

-- PCP-12722: Add new column checkpointed_version to v3_archived_capability_instances table
ALTER TABLE V3_ARCHIVED_CAPABILITY_INSTANCES ADD COLUMN IF NOT EXISTS CHECKPOINTED_VERSION BOOLEAN DEFAULT FALSE;

-- Function to set CHECKPOINTED_VERSION to TRUE after insert
CREATE OR REPLACE FUNCTION V3_SET_CHECKPOINTED_VERSION_TRUE()
RETURNS TRIGGER AS $$
BEGIN
    NEW.CHECKPOINTED_VERSION := TRUE;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

-- Trigger to call the function after insert
DROP TRIGGER IF EXISTS V3_SET_CHECKPOINTED_VERSION_TRUE_TRIGGER ON V3_ARCHIVED_CAPABILITY_INSTANCES;
CREATE TRIGGER V3_SET_CHECKPOINTED_VERSION_TRUE_TRIGGER
    BEFORE INSERT ON V3_ARCHIVED_CAPABILITY_INSTANCES
    FOR EACH ROW
    EXECUTE FUNCTION V3_SET_CHECKPOINTED_VERSION_TRUE();

-- Update database schema at the end (earlier version is 1.10.0 i.e. 13)
UPDATE schema_version SET version = 14;
