-- Database schema changes for 1.16.0

--
-- V3_FEATURE_METAFATA
--

CREATE TABLE IF NOT EXISTS V3_FEATURE_METADATA (
    FEATURE_ID VARCHAR(255) NOT NULL,
    VERSION int[] NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_TIME BIGINT,
    MODIFIED_TIME BIGINT,
    CREATED_BY VARCHAR(255),
    MODIFIED_BY VARCHAR(255),

    CONSTRAINT V3_FEATURE_METADATA_PKEY PRIMARY KEY (FEATURE_ID, VERSION)
);

DROP TRIGGER IF EXISTS SET_CREATED_BY ON V3_FEATURE_METADATA;
CREATE TRIGGER SET_CREATED_BY BEFORE INSERT ON V3_FEATURE_METADATA FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_MODIFIER();

DROP TRIGGER IF EXISTS SET_MODIFIED_BY ON V3_FEATURE_METADATA;
CREATE TRIGGER SET_MODIFIED_BY BEFORE UPDATE ON V3_FEATURE_METADATA FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_MODIFIER();

DROP TRIGGER IF EXISTS SET_CREATED_TIME ON V3_FEATURE_METADATA;
CREATE TRIGGER SET_CREATED_TIME BEFORE INSERT ON V3_FEATURE_METADATA FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_CREATED_TIME();

DROP TRIGGER IF EXISTS SET_MODIFIED_TIME ON V3_FEATURE_METADATA;
CREATE TRIGGER SET_MODIFIED_TIME BEFORE UPDATE ON V3_FEATURE_METADATA FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_MODIFIED_TIME();

-- add AI as an web feature to V3_FEATURE_METADATA
INSERT INTO V3_FEATURE_METADATA(FEATURE_ID, VERSION, DISPLAY_NAME, DESCRIPTION)
VALUES ('TESSA', '{1,0,0}', 'TESSA AI Agent', 'TESSA AI Agent')
ON CONFLICT DO NOTHING;

--
-- V3_FEATURE_INSTANCES
--

CREATE TABLE IF NOT EXISTS V3_FEATURE_INSTANCES (
    FEATURE_INSTANCE_ID VARCHAR(255) NOT NULL,
    FEATURE_ID VARCHAR(255) NOT NULL,
    SUBSCRIPTION_ID VARCHAR(255) NOT NULL,
    VERSION int[] NOT NULL,
    ENABLED BOOLEAN,
    ACTIVATED BOOLEAN,
    CONFIGURED BOOLEAN,
    CREATED_TIME BIGINT,
    MODIFIED_TIME BIGINT,
    CREATED_BY VARCHAR(255),
    MODIFIED_BY VARCHAR(255),
    FEATURE_INSTANCE_NAME VARCHAR(255),
    FEATURE_INSTANCE_DESCRIPTION VARCHAR(255),
    
    CONSTRAINT V3_FEATURE_INSTANCES_PKEY PRIMARY KEY (FEATURE_INSTANCE_ID, FEATURE_ID, SUBSCRIPTION_ID),
    CONSTRAINT V3_FEATURE_INSTANCES_FK0 FOREIGN KEY (FEATURE_ID,VERSION) REFERENCES V3_FEATURE_METADATA(FEATURE_ID,VERSION),
    CONSTRAINT V3_FEATURE_INSTANCES_FK1 FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES V2_SUBSCRIPTIONS(SUBSCRIPTION_ID)
);

ALTER TABLE V3_FEATURE_INSTANCES
ADD COLUMN IF NOT EXISTS EULA BOOLEAN;

DROP TRIGGER IF EXISTS SET_CREATED_BY ON V3_FEATURE_INSTANCES;
CREATE TRIGGER SET_CREATED_BY BEFORE INSERT ON V3_FEATURE_INSTANCES FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_MODIFIER();

DROP TRIGGER IF EXISTS SET_MODIFIED_BY ON V3_FEATURE_INSTANCES;
CREATE TRIGGER SET_MODIFIED_BY BEFORE UPDATE ON V3_FEATURE_INSTANCES FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_MODIFIER();

DROP TRIGGER IF EXISTS SET_CREATED_TIME ON V3_FEATURE_INSTANCES;
CREATE TRIGGER SET_CREATED_TIME BEFORE INSERT ON V3_FEATURE_INSTANCES FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_CREATED_TIME();

DROP TRIGGER IF EXISTS SET_MODIFIED_TIME ON V3_FEATURE_INSTANCES;
CREATE TRIGGER SET_MODIFIED_TIME BEFORE UPDATE ON V3_FEATURE_INSTANCES FOR EACH ROW EXECUTE PROCEDURE TRIGGER_SET_MODIFIED_TIME();

-- CLEANUP V3_FEATURE_INSTANCES TABLE
CREATE OR REPLACE FUNCTION CLEANUP_SUBSCRIPTION_FEATURES()
RETURNS TRIGGER
LANGUAGE plpgsql AS
$$
BEGIN
DELETE FROM V3_FEATURE_INSTANCES
WHERE subscription_id = OLD.subscription_id;

RETURN OLD;
END;
$$;

-- ON V2_SUBSCRIPTIONS
DROP TRIGGER IF EXISTS CLEANUP_FEATURE_INSTANCES_SUB ON V2_SUBSCRIPTIONS;
CREATE TRIGGER CLEANUP_FEATURE_INSTANCES_SUB
    BEFORE DELETE ON V2_SUBSCRIPTIONS
    FOR EACH ROW
    EXECUTE FUNCTION CLEANUP_SUBSCRIPTION_FEATURES();

--Re-create V3_VIEW_APPS_ON_SUBSCRIPTIONS view as we have to change capability instance version to apps table capability instance version.
DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_APPS_ON_SUBSCRIPTIONS;

CREATE MATERIALIZED VIEW V3_VIEW_APPS_ON_SUBSCRIPTIONS
AS
SELECT
    SUB.SUBSCRIPTION_ID,
    DP.DP_ID,
    DP.NAME as dp_name,
    DP.DESCRIPTION as dp_description,
    DP.HOST_CLOUD_TYPE,
    DP.STATUS as dp_status,
    DP.REGISTERED_REGION,
    DP.RUNNING_REGION,
    DP.TAGS as dp_tags,
    CI.CAPABILITY_INSTANCE_ID,
    CI.CAPABILITY_INSTANCE_NAME,
    CI.CAPABILITY_ID,
    CI.CAPABILITY_INSTANCE_DESCRIPTION,
    CI.NAMESPACE as capability_instance_namespace,
    CI.STATUS as capability_instance_status,
    CI.TAGS as capability_instance_tags,
    APPS.CAPABILITY_VERSION as capability_instance_version,
    APPS.APP_ID,
    APPS.APP_NAME,
    APPS.APP_DESCRIPTION,
    APPS.APP_VERSION,
    APPS.STATE as app_state,
    APPS.DESIRED_REPLICAS,
    APPS.TAGS as app_tags,
    APPS.APP_LINKS,
    APPS.EULA as app_eula,
    APPS.RESOURCE_INSTANCE_IDS as app_resource_instance_ids,
    APPS.CREATED_TIME,
    APPS.MODIFIED_TIME,
    APPS.NAMESPACE as app_namespace,
    (select CONCAT(U.firstname || ' ',lastname) from v2_users U where U.USER_ENTITY_ID = APPS.MODIFIED_BY)
        as modified_by,
    (select CONCAT(U.firstname|| ' ',lastname) from v2_users U where U.USER_ENTITY_ID = APPS.CREATED_BY)
        as created_by
FROM V2_SUBSCRIPTIONS SUB JOIN V3_DATA_PLANES DP ON SUB.SUBSCRIPTION_ID = DP.SUBSCRIPTION_ID
                          JOIN V3_CAPABILITY_INSTANCES CI ON DP.DP_ID = CI.DP_ID
                          JOIN V3_APPS APPS ON CI.CAPABILITY_INSTANCE_ID = APPS.CAPABILITY_INSTANCE_ID
    WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS V3_VIEW_APPS_ON_SUBSCRIPTIONS_INDEX ON V3_VIEW_APPS_ON_SUBSCRIPTIONS (SUBSCRIPTION_ID,REGISTERED_REGION,DP_ID,CAPABILITY_INSTANCE_ID,APP_ID);


-- Update database schema at the end (earlier version is 1.15.0 i.e. 18)
UPDATE schema_version SET version = 19;
