-- Database schema changes for 1.17.0

DROP MATERIALIZED VIEW IF EXISTS V4_VIEW_DATA_PLANE_MONITOR_DETAILS CASCADE;
CREATE MATERIALIZED VIEW V4_VIEW_DATA_PLANE_MONITOR_DETAILS AS
select VDP.SUBSCRIPTION_ID,VDP.DP_ID,VDP.REGISTERED_REGION,VDP.HOST_CLOUD_TYPE,VDP.STATUS AS DP_STATUS,row_to_json((
    SELECT ColumnName FROM ( SELECT
                                 VDP.NAME, VDP.RUNNING_REGION, VDP.DP_CONFIG, VDP.NAMESPACES, DPCP.CAPABILITIES, VRI.RESOURCE_INSTANCES)
                               AS ColumnName (NAME, RUNNING_REGION, DP_CONFIG, NAMESPACES, CAPABILITIES, RESOURCE_INSTANCES)
)) AS DATAPLANES FROM V3_DATA_PLANES VDP
                          LEFT JOIN ( SELECT DP_ID, json_agg(row_to_json((SELECT ColumnName FROM (SELECT
                                                                                                      CAPABILITY_INSTANCE_ID, CAPABILITY_INSTANCE_NAME, CAPABILITY_INSTANCE_DESCRIPTION, CAPABILITY_ID, DISPLAY_NAME,
                                                                                                      CAPABILITY_TYPE, CAPABILITY_INSTANCE_METADATA, NAMESPACE, VERSION, STATUS, REGION, TAGS
                                                                                                 ) AS ColumnName (CAPABILITY_INSTANCE_ID, CAPABILITY_INSTANCE_NAME, CAPABILITY_INSTANCE_DESCRIPTION, CAPABILITY_ID, NAME, CAPABILITY_TYPE, CAPABILITY_INSTANCE_METADATA, NAMESPACE, VERSION, STATUS, REGION, TAGS)
))) AS CAPABILITIES
                                      FROM V3_CAPABILITY_INSTANCES CI LEFT JOIN V3_CAPABILITY_METADATA CR USING (CAPABILITY_ID, CAPABILITY_TYPE)
                                      GROUP BY DP_ID
) DPCP ON VDP.DP_ID = DPCP.DP_ID
                          LEFT JOIN (SELECT SCOPE_ID, json_agg(row_to_json((SELECT ColumnName
                                                                            FROM (SELECT RESOURCE_INSTANCE_ID, RESOURCE_ID, RESOURCE_INSTANCE_METADATA) AS ColumnName (RESOURCE_INSTANCE_ID, RESOURCE_ID, RESOURCE_INSTANCE_METADATA)
))) AS RESOURCE_INSTANCES FROM V3_RESOURCE_INSTANCES
                                     WHERE SCOPE = 'DATAPLANE'
                                       AND (RESOURCE_ID = 'HAWKDOMAIN' OR RESOURCE_ID = 'BW6TEAAGENT' OR RESOURCE_ID = 'BETEAAGENT' OR RESOURCE_ID = 'MSGSERVER')
                                     GROUP BY SCOPE_ID
) VRI ON VDP.DP_ID = VRI.SCOPE_ID
    WITH DATA;

CREATE UNIQUE INDEX V4_VIEW_DATA_PLANE_MONITOR_DETAILS_INDEX ON V4_VIEW_DATA_PLANE_MONITOR_DETAILS (DP_ID);


DROP FUNCTION IF EXISTS V4_VIEW_DATA_PLANE_MONITOR_DETAILS_REFRESH() CASCADE;
CREATE FUNCTION V4_VIEW_DATA_PLANE_MONITOR_DETAILS_REFRESH()
    RETURNS TRIGGER
    LANGUAGE plpgsql
	AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY V4_VIEW_DATA_PLANE_MONITOR_DETAILS;
RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS V4_VIEW_DATA_PLANE_MONITOR_DETAILS_SH_TRIGGER ON V3_DATA_PLANES;
CREATE TRIGGER V4_VIEW_DATA_PLANE_MONITOR_DETAILS_SH_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
              ON V3_DATA_PLANES
                  FOR EACH STATEMENT EXECUTE PROCEDURE V4_VIEW_DATA_PLANE_MONITOR_DETAILS_REFRESH();

DROP TRIGGER IF EXISTS V4_VIEW_DATA_PLANE_MONITOR_DETAILS_CAPABILITY_TRIGGER ON V3_CAPABILITY_METADATA;
CREATE TRIGGER V4_VIEW_DATA_PLANE_MONITOR_DETAILS_CAPABILITY_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
              ON V3_CAPABILITY_METADATA
                  FOR EACH STATEMENT EXECUTE PROCEDURE V4_VIEW_DATA_PLANE_MONITOR_DETAILS_REFRESH();

DROP TRIGGER IF EXISTS V4_VIEW_DATA_PLANE_MONITOR_DETAILS_CI_TRIGGER ON V3_CAPABILITY_INSTANCES;
CREATE TRIGGER V4_VIEW_DATA_PLANE_MONITOR_DETAILS_CI_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
              ON V3_CAPABILITY_INSTANCES
                  FOR EACH STATEMENT EXECUTE PROCEDURE V4_VIEW_DATA_PLANE_MONITOR_DETAILS_REFRESH();

DROP TRIGGER IF EXISTS V4_VIEW_DATA_PLANE_MONITOR_DETAILS_RI_TRIGGER ON V3_RESOURCE_INSTANCES;
CREATE TRIGGER V4_VIEW_DATA_PLANE_MONITOR_DETAILS_RI_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
              ON V3_RESOURCE_INSTANCES
                  FOR EACH STATEMENT EXECUTE PROCEDURE V4_VIEW_DATA_PLANE_MONITOR_DETAILS_REFRESH();

-- Refresh materialized view V3_VIEW_DATA_PLANE_MONITOR_DETAILS_CAPABILITY
DROP TRIGGER IF EXISTS V3_VIEW_DATA_PLANE_MONITOR_DETAILS_CAPABILITY_TRIGGER ON V3_CAPABILITY_METADATA;
CREATE TRIGGER V3_VIEW_DATA_PLANE_MONITOR_DETAILS_CAPABILITY_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
              ON V3_CAPABILITY_METADATA
                  FOR EACH STATEMENT EXECUTE PROCEDURE V3_VIEW_DATA_PLANE_MONITOR_DETAILS_REFRESH();

-- Database schema changes for webhook receiver support

-- Add WEBHOOK_RECEIVER resource type
INSERT INTO v3_resources (RESOURCE_ID, NAME, DESCRIPTION, TYPE, RESOURCE_METADATA, HOST_CLOUD_TYPE, RESOURCE_LEVEL)
VALUES ('WEBHOOK_RECEIVER', 'WEBHOOK RECEIVER Resource', 'WEBHOOK RECEIVER Resource', 'alerts_receiver', 
    '{"fields": [ { "key": "enabled", "name": "Enabled", "value": true, "dataType": "boolean", "required": true }, { "key": "url", "name": "Webhook URL", "dataType": "string", "required": true }, { "key": "headers", "name": "Custom Headers", "dataType": "object", "required": false }, { "key": "timeout", "name": "Timeout (seconds)", "dataType": "integer", "required": false }, { "key": "max_alerts", "name": "Max Alerts", "dataType": "integer", "required": false }, { "key": "type", "name": "Type", "dataType": "string", "required": true } ] }', 
    '{"k8s"}', 'PLATFORM')
ON CONFLICT DO NOTHING;

-- Update V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER to include WEBHOOK_RECEIVER
-- Note: View name kept for backward compatibility, now supports both EMAIL_RECEIVER and WEBHOOK_RECEIVER
DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER;
CREATE MATERIALIZED VIEW V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER
AS
SELECT
    AR.RESOURCE_INSTANCE_ID AS RESOURCE_INSTANCE_ID,
    AR.RESOURCE_ID AS RESOURCE_ID,
    AR.RESOURCE_INSTANCE_NAME AS RESOURCE_INSTANCE_NAME,
    AR.RESOURCE_INSTANCE_DESCRIPTION AS RESOURCE_INSTANCE_DESCRIPTION,
    AR.RESOURCE_INSTANCE_METADATA AS RESOURCE_INSTANCE_METADATA,
    AR.SCOPE AS SCOPE,
    AR.REGION AS REGION,
    AR.SCOPE_ID AS SUBSCRIPTION_ID,
    ER.RESOURCE_INSTANCE_ID AS EMAIL_RECEIVER_ID,
    ER.RESOURCE_INSTANCE_NAME AS EMAIL_RECEIVER_NAME,
    ER.RESOURCE_INSTANCE_DESCRIPTION AS EMAIL_RECEIVER_DESCRIPTION,
    ER.RESOURCE_INSTANCE_METADATA AS EMAIL_RECEIVER_METADATA,
    DP.NAME AS DP_NAME,
    CASE
        WHEN COUNT(DP.DP_ID) = 0 THEN NULL
        ELSE json_agg(
                json_build_object(
                        'dp_id', DP.DP_ID,
                        'name', DP.NAME,
                        'description', DP.DESCRIPTION,
                        'registered_region', DP.REGISTERED_REGION,
                        'running_region', DP.RUNNING_REGION
                )
             )
        END AS DP_DETAILS
FROM
    V3_RESOURCE_INSTANCES AR
        JOIN
    V3_ALERT_RULES_TO_RECEIVERS ARR
    ON AR.RESOURCE_INSTANCE_ID = ARR.RULE_ID
        JOIN
    V3_RESOURCE_INSTANCES ER
    ON ARR.RECEIVER_ID = ER.RESOURCE_INSTANCE_ID
        LEFT JOIN V3_DATA_PLANES DP
                  ON DP.DP_ID = (
                      SELECT value->>'value'
                      FROM jsonb_array_elements(AR.RESOURCE_INSTANCE_METADATA->'fields') AS fields
                      WHERE fields->>'key' = 'dpId'
                  )
WHERE
    AR.RESOURCE_ID = 'ALERT_RULE'
  AND ER.RESOURCE_ID IN ('EMAIL_RECEIVER', 'WEBHOOK_RECEIVER')
GROUP BY
    AR.RESOURCE_INSTANCE_ID, AR.RESOURCE_ID, AR.RESOURCE_INSTANCE_NAME, AR.RESOURCE_INSTANCE_DESCRIPTION,
    AR.RESOURCE_INSTANCE_METADATA, AR.SCOPE, AR.REGION, AR.SCOPE_ID, DP.NAME,
    ER.RESOURCE_INSTANCE_ID, ER.RESOURCE_INSTANCE_NAME, ER.RESOURCE_INSTANCE_DESCRIPTION, ER.RESOURCE_INSTANCE_METADATA
    WITH DATA;

CREATE UNIQUE INDEX V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_INDEX
    ON V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER USING btree (RESOURCE_INSTANCE_ID, EMAIL_RECEIVER_ID);

-- Recreate refresh function (CASCADE dropped it with the view)
DROP FUNCTION IF EXISTS V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_REFRESH() CASCADE;
CREATE FUNCTION V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_REFRESH()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER;
    RETURN NULL;
END;
$$;

-- Recreate triggers
DROP TRIGGER IF EXISTS V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_RI_TRIGGER ON V3_RESOURCE_INSTANCES;
CREATE TRIGGER V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_RI_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
    ON V3_RESOURCE_INSTANCES
    FOR EACH STATEMENT
    EXECUTE PROCEDURE V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_REFRESH();

DROP TRIGGER IF EXISTS V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_ALERT_RULE_TO_RECEIVER_TRIGGER ON V3_ALERT_RULES_TO_RECEIVERS;
CREATE TRIGGER V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_ALERT_RULE_TO_RECEIVER_TRIGGER
    AFTER INSERT OR UPDATE OR DELETE
    ON V3_ALERT_RULES_TO_RECEIVERS
    FOR EACH STATEMENT
    EXECUTE PROCEDURE V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_REFRESH();

DROP TRIGGER IF EXISTS V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_DATA_PLANES_TRIGGER ON V3_DATA_PLANES;
CREATE TRIGGER V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_DATA_PLANES_TRIGGER
    AFTER INSERT OR UPDATE OR DELETE
    ON V3_DATA_PLANES
    FOR EACH STATEMENT
    EXECUTE PROCEDURE V3_VIEW_ALERT_RULE_WITH_EMAIL_RECEIVER_REFRESH();

-- Update V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE to include WEBHOOK_RECEIVER
DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE;
CREATE MATERIALIZED VIEW V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE
AS
SELECT
    ER.RESOURCE_INSTANCE_ID AS RESOURCE_INSTANCE_ID,
    ER.RESOURCE_ID AS RESOURCE_ID,
    ER.RESOURCE_INSTANCE_NAME AS RESOURCE_INSTANCE_NAME,
    ER.RESOURCE_INSTANCE_DESCRIPTION AS RESOURCE_INSTANCE_DESCRIPTION,
    ER.RESOURCE_INSTANCE_METADATA AS RESOURCE_INSTANCE_METADATA,
    ER.SCOPE AS SCOPE,
    ER.SCOPE_ID AS SUBSCRIPTION_ID,
    ER.REGION AS REGION,
    CASE
        WHEN COUNT(AR.RESOURCE_INSTANCE_ID) = 0 THEN NULL
        ELSE json_agg(
                json_build_object(
                        'alert_rule_id', AR.RESOURCE_INSTANCE_ID,
                        'alert_rule_name', AR.RESOURCE_INSTANCE_NAME,
                        'alert_rule_description', AR.RESOURCE_INSTANCE_DESCRIPTION,
                        'alert_rule_metadata', AR.RESOURCE_INSTANCE_METADATA,
                        'scope', AR.SCOPE,
                        'region', AR.REGION,
                        'subscription_id', AR.SCOPE_ID
                )
             )
        END AS ALERT_RULE_DETAILS
FROM
    V3_RESOURCE_INSTANCES ER
        LEFT JOIN
    V3_ALERT_RULES_TO_RECEIVERS ARR
    ON ER.RESOURCE_INSTANCE_ID = ARR.RECEIVER_ID
        LEFT JOIN
    V3_RESOURCE_INSTANCES AR
    ON ARR.RULE_ID = AR.RESOURCE_INSTANCE_ID
WHERE
    ER.RESOURCE_ID IN ('EMAIL_RECEIVER', 'WEBHOOK_RECEIVER')
GROUP BY
    ER.RESOURCE_INSTANCE_ID, ER.RESOURCE_ID, ER.RESOURCE_INSTANCE_NAME, ER.RESOURCE_INSTANCE_DESCRIPTION,
    ER.RESOURCE_INSTANCE_METADATA, ER.SCOPE, ER.SCOPE_ID, ER.REGION
    WITH DATA;

CREATE UNIQUE INDEX V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_INDEX
    ON V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE USING btree (RESOURCE_INSTANCE_ID);

-- Recreate refresh function
DROP FUNCTION IF EXISTS V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_REFRESH() CASCADE;
CREATE FUNCTION V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_REFRESH()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE;
    RETURN NULL;
END;
$$;

-- Recreate triggers
DROP TRIGGER IF EXISTS V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_RI_TRIGGER ON V3_RESOURCE_INSTANCES;
CREATE TRIGGER V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_RI_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
    ON V3_RESOURCE_INSTANCES
    FOR EACH STATEMENT
    EXECUTE PROCEDURE V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_REFRESH();

DROP TRIGGER IF EXISTS V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_ALERT_RULE_TO_RECEIVER_TRIGGER ON V3_ALERT_RULES_TO_RECEIVERS;
CREATE TRIGGER V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_ALERT_RULE_TO_RECEIVER_TRIGGER
    AFTER INSERT OR UPDATE OR DELETE
    ON V3_ALERT_RULES_TO_RECEIVERS
    FOR EACH STATEMENT
    EXECUTE PROCEDURE V3_VIEW_EMAIL_RECEIVER_WITH_ALERT_RULE_REFRESH();

-- PCP-17036/17463 adding monitoring status column to below tables

ALTER TABLE V3_CAPABILITY_INSTANCES ADD COLUMN IF NOT EXISTS MONITORING_STATUS VARCHAR(255);
ALTER TABLE V3_RESOURCE_INSTANCES ADD COLUMN IF NOT EXISTS MONITORING_STATUS VARCHAR(255);
ALTER TABLE V3_DATA_PLANES ADD COLUMN IF NOT EXISTS MONITORING_STATUS VARCHAR(255);

-- PCP-17463

DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES CASCADE;
CREATE MATERIALIZED VIEW V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES
AS
SELECT
    DP.SUBSCRIPTION_ID,
    DP.DP_ID,
    DP.NAMESPACES,
    DP.NAME,
    DP.DESCRIPTION,
    DP.HOST_CLOUD_TYPE,
    DP.DP_CONFIG,
    DP.STATUS,
    DP.MONITORING_STATUS,
    DP.REGISTERED_REGION,
    DP.RUNNING_REGION,
    DP.MODIFIED_DATE,
    DP.TAGS,
    DP.CONTAINER_REGISTRY_CREDENTIAL,
    DP.CONNECTION_DETAILS,
    CI.CAPABILITIES,
    AA.APPS,
    RI.RESOURCE_INSTANCE_METADATA
FROM ((
    V3_DATA_PLANES DP
        LEFT JOIN (
        SELECT DP_ID, json_agg(row_to_json((
            SELECT ColumnName
            FROM (SELECT CAPABILITY_INSTANCE_ID, CAPABILITY_INSTANCE_NAME, CAPABILITY_INSTANCE_DESCRIPTION, CAPABILITY_ID, DISPLAY_NAME, CR.CAPABILITY_TYPE, NAMESPACE, CI.VERSION, STATUS, REGION, TAGS, CI.MODIFIED_TIME,CI.MONITORING_STATUS)
                     AS ColumnName (CAPABILITY_INSTANCE_ID, CAPABILITY_INSTANCE_NAME, CAPABILITY_INSTANCE_DESCRIPTION, CAPABILITY_ID, CAPABILITY_NAME, CAPABILITY_TYPE, NAMESPACE, VERSION, STATUS, REGION, TAGS, MODIFIED_TIME,MONITORING_STATUS)
        ))) CAPABILITIES
        FROM (V3_CAPABILITY_INSTANCES CI LEFT JOIN V3_CAPABILITY_METADATA CR USING (CAPABILITY_ID, CAPABILITY_TYPE))
        GROUP BY DP_ID) CI USING (DP_ID)
        LEFT JOIN (
        SELECT DP_ID, json_agg(row_to_json((
            SELECT ColumnName
            FROM (SELECT APP_ID, APP_NAME, APP_VERSION, CAPABILITY_INSTANCE_ID, CAPABILITY_ID, CAPABILITY_VERSION, STATE, TAGS, A.MODIFIED_TIME)
                     AS ColumnName (APP_ID, APP_NAME, APP_VERSION, CAPABILITY_INSTANCE_ID, CAPABILITY_ID, CAPABILITY_VERSION, STATE, TAGS, MODIFIED_TIME)
        ))) APPS
        FROM V3_APPS A
        GROUP BY DP_ID) AA USING (DP_ID)
    ))
         LEFT JOIN V3_RESOURCE_INSTANCES RI ON RI.SCOPE='DATAPLANE' AND RI.SCOPE_ID=DP.DP_ID AND RI.RESOURCE_ID='SERVICEACCOUNT' AND RESOURCE_LEVEL='INFRA'
    WITH DATA;

CREATE UNIQUE INDEX VIEW_DATA_PLANE_CAPABILITY_INSTANCE_INDEX ON V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES (DP_ID);

REFRESH MATERIALIZED VIEW V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES;

-- Update database schema at the end (earlier version is 1.16.0 i.e. 19)
UPDATE schema_version SET version = 20;
