-- Copyright (c) 2023-2026. Cloud Software Group, Inc.
-- This file is subject to the license terms contained
-- in the license file that is distributed with this file.

-- Rollback database schema changes for 1.19.0 (reverse of 22-up.sql)
--
-- NOTE: This restores the schema to its post-21 (1.18.0) state. Objects that
--       22-up created are dropped; objects that 22-up dropped/replaced are
--       recreated using their immediate-predecessor (21-up.sql / 18-up.sql)
--       definitions.

-- ============================================================================
-- PHASE 1: Drop objects newly added in 22-up
-- ============================================================================

-- 1a. V3_VIEW_RESOURCE_INSTANCE_LINKED_ENTITIES (new consolidated matview in 22-up)
--     CASCADE drops its unique index; refresh function drop removes nothing extra.
DROP TRIGGER IF EXISTS V3_VIEW_RESOURCE_INSTANCE_LINKED_ENTITIES_RI_TRIGGER ON V3_RESOURCE_INSTANCES;
DROP TRIGGER IF EXISTS V3_VIEW_RESOURCE_INSTANCE_LINKED_ENTITIES_DP_TRIGGER ON V3_DATA_PLANES;
DROP TRIGGER IF EXISTS V3_VIEW_RESOURCE_INSTANCE_LINKED_ENTITIES_CI_TRIGGER ON V3_CAPABILITY_INSTANCES;
DROP FUNCTION IF EXISTS V3_VIEW_RESOURCE_INSTANCE_LINKED_ENTITIES_REFRESH() CASCADE;
DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_RESOURCE_INSTANCE_LINKED_ENTITIES CASCADE;

-- 1b. Resource-instance delete-validation trigger + function (new in 22-up)
DROP TRIGGER IF EXISTS V3_VALIDATE_RESOURCE_INSTANCE_DELETE_TRIGGER ON V3_RESOURCE_INSTANCES;
DROP FUNCTION IF EXISTS V3_VALIDATE_RESOURCE_INSTANCE_DELETE() CASCADE;

-- 1c. Indexes created in 22-up
DROP INDEX IF EXISTS idx_data_planes_resource_instance_ids_gin;
DROP INDEX IF EXISTS idx_apps_resource_instance_ids_gin;
DROP INDEX IF EXISTS idx_data_planes_subscription_id;
DROP INDEX IF EXISTS idx_capability_instances_dp_id;
DROP INDEX IF EXISTS idx_resource_instances_scope_for_linked_entities;

-- ============================================================================
-- PHASE 2: Restore V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE to its 21-up definition
--   22-up added the CI.MONITORING_STATUS column and used CI.NAMESPACE directly.
--   The pre-22 (21-up) definition derives NAMESPACE from the linked NAMESPACE
--   resource instance and has no MONITORING_STATUS column.
-- ============================================================================

DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE CASCADE;
CREATE MATERIALIZED VIEW V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE
AS
SELECT
    DP.SUBSCRIPTION_ID,
    DP.DP_ID,
    DP.NAME AS DP_NAME,
    CI.CAPABILITY_ID,
    (SELECT f->>'value'
     FROM V3_RESOURCE_INSTANCES RI,
          jsonb_array_elements(RI.RESOURCE_INSTANCE_METADATA->'fields') AS f
     WHERE RI.RESOURCE_INSTANCE_ID = ANY(CI.RESOURCE_INSTANCE_IDS)
       AND RI.RESOURCE_ID = 'NAMESPACE'
       AND f->>'key' = 'namespaceName'
     ORDER BY CASE WHEN RI.RESOURCE_INSTANCE_METADATA->'fields' @> '[{"key":"isPrimary","value":true}]'::jsonb THEN 0 ELSE 1 END
     LIMIT 1) AS NAMESPACE,
    CI.VERSION,
    CI.STATUS,
    CI.REGION,
    CI.CREATED_TIME,
    CI.MODIFIED_TIME,
    (select CONCAT(U.firstname || ' ',lastname) from v2_users U where U.USER_ENTITY_ID = CI.MODIFIED_BY)
        as MODIFIED_BY,
    (select CONCAT(U.firstname|| ' ',lastname) from v2_users U where U.USER_ENTITY_ID = CI.CREATED_BY)
        as CREATED_BY,
    CI.TAGS,
    CI.CAPABILITY_INSTANCE_ID,
    CI.CAPABILITY_INSTANCE_NAME,
    CI.CAPABILITY_INSTANCE_DESCRIPTION,
    COALESCE(
            (
                SELECT JSON_AGG(
                               JSON_BUILD_OBJECT(
                                       'id', RI.RESOURCE_INSTANCE_ID,
                                       'name', RI.RESOURCE_INSTANCE_NAME
                               )
                       )
                FROM V3_RESOURCE_INSTANCES RI
                WHERE RI.RESOURCE_INSTANCE_ID = ANY(CI.RESOURCE_INSTANCE_IDS)
            ),
            '[]'::JSON
    ) AS "resource_instances",
    CI.CAPABILITY_TYPE
FROM V3_CAPABILITY_INSTANCES CI
         LEFT JOIN V3_DATA_PLANES DP
                   USING(DP_ID)
WHERE CI.CAPABILITY_TYPE = 'PLATFORM'
    WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_INDEX ON V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE
    (SUBSCRIPTION_ID, DP_ID,CAPABILITY_INSTANCE_ID);

CREATE OR REPLACE FUNCTION V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_REFRESH()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE;
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_CI_TRIGGER ON V3_CAPABILITY_INSTANCES;
CREATE TRIGGER V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_CI_TRIGGER AFTER
    INSERT OR DELETE OR UPDATE OF DP_ID, CAPABILITY_INSTANCE_ID, CAPABILITY_ID, CAPABILITY_TYPE, VERSION, STATUS, REGION, CREATED_TIME, MODIFIED_TIME, CREATED_BY, MODIFIED_BY, TAGS, CAPABILITY_INSTANCE_NAME, CAPABILITY_INSTANCE_DESCRIPTION, RESOURCE_INSTANCE_IDS
              ON V3_CAPABILITY_INSTANCES
                  FOR EACH STATEMENT
                  EXECUTE PROCEDURE V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_REFRESH();

DROP TRIGGER IF EXISTS V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_DP_TRIGGER ON V3_DATA_PLANES;
CREATE TRIGGER V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_DP_TRIGGER
    AFTER INSERT OR DELETE OR UPDATE OF SUBSCRIPTION_ID, DP_ID, NAME
                    ON V3_DATA_PLANES
                        FOR EACH STATEMENT
                        EXECUTE PROCEDURE V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_REFRESH();

DROP TRIGGER IF EXISTS V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_RI_TRIGGER ON V3_RESOURCE_INSTANCES;
CREATE TRIGGER V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_RI_TRIGGER
    AFTER INSERT OR UPDATE OR DELETE
                    ON V3_RESOURCE_INSTANCES
                        FOR EACH STATEMENT
                        EXECUTE PROCEDURE V3_VIEW_CAPABILITY_INSTANCE_DATA_PLANE_REFRESH();

-- ============================================================================
-- PHASE 2a (PCP-20891): Re-add the six dropped NAMESPACE / NAMESPACES columns
--   All NULLABLE — matches the post-21-up.sql:67-75 state. Columns come back
--   empty; no code has written to them since PCP-10813 so this is faithful.
--   Done before PHASE 2b restorations so any trigger / view recreation that
--   references the column names finds them present.
-- ============================================================================

ALTER TABLE V3_DATA_PLANES                     ADD COLUMN IF NOT EXISTS NAMESPACES TEXT[];
ALTER TABLE V3_ARCHIVED_DATA_PLANES            ADD COLUMN IF NOT EXISTS NAMESPACES TEXT[];
ALTER TABLE V3_CAPABILITY_INSTANCES            ADD COLUMN IF NOT EXISTS NAMESPACE  VARCHAR(255);
ALTER TABLE V3_ARCHIVED_CAPABILITY_INSTANCES   ADD COLUMN IF NOT EXISTS NAMESPACE  VARCHAR(255);
ALTER TABLE V3_APPS                            ADD COLUMN IF NOT EXISTS NAMESPACE  VARCHAR(255);
ALTER TABLE V3_ARCHIVED_APPS                   ADD COLUMN IF NOT EXISTS NAMESPACE  VARCHAR(255);

-- ============================================================================
-- PHASE 2b (PCP-20891): Restore V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES to its
--   21-up.sql definition — CREATED_DATE removed from SELECT; DP trigger
--   UPDATE OF list restored to the 21-up.sql:577-581 column set.
-- ============================================================================

DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES CASCADE;
CREATE MATERIALIZED VIEW V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES AS
WITH
ns_ri AS (
    SELECT
        RI.RESOURCE_INSTANCE_ID,
        RI.SCOPE_ID                 AS dp_id,
        RI.RESOURCE_INSTANCE_NAME   AS namespace_name,
        CASE WHEN RI.RESOURCE_INSTANCE_METADATA->'fields'
                  @> '[{"key":"isPrimary","value":true}]'::jsonb
             THEN 0 ELSE 1 END      AS primary_order
    FROM V3_RESOURCE_INSTANCES RI
    WHERE RI.RESOURCE_ID = 'NAMESPACE'
      AND RI.SCOPE       = 'DATAPLANE'
),
dp_ns AS (
    SELECT dp_id,
           ARRAY_AGG(namespace_name ORDER BY primary_order) AS namespaces
    FROM   ns_ri
    GROUP  BY dp_id
),
ci_ns AS (
    SELECT DISTINCT ON (CI.CAPABILITY_INSTANCE_ID)
        CI.CAPABILITY_INSTANCE_ID,
        NS.namespace_name
    FROM  V3_CAPABILITY_INSTANCES CI,
          unnest(CI.RESOURCE_INSTANCE_IDS) AS ri_id
    JOIN  ns_ri NS ON NS.resource_instance_id = ri_id
    ORDER BY CI.CAPABILITY_INSTANCE_ID, NS.primary_order
),
ci_flat AS (
    SELECT
        CI.DP_ID,
        CI.CAPABILITY_INSTANCE_ID,
        CI.CAPABILITY_INSTANCE_NAME,
        CI.CAPABILITY_INSTANCE_DESCRIPTION,
        CI.CAPABILITY_ID,
        CI.VERSION,
        CI.STATUS,
        CI.REGION,
        CI.TAGS,
        CI.MODIFIED_TIME,
        CI.MONITORING_STATUS,
        CR.DISPLAY_NAME,
        CR.CAPABILITY_TYPE,
        cn.namespace_name AS namespace
    FROM  V3_CAPABILITY_INSTANCES CI
    LEFT  JOIN V3_CAPABILITY_METADATA CR USING (CAPABILITY_ID, CAPABILITY_TYPE)
    LEFT  JOIN ci_ns cn            USING (CAPABILITY_INSTANCE_ID)
),
ci_agg AS (
    SELECT
        cf.DP_ID,
        json_agg(row_to_json((
            SELECT ColumnName
            FROM (
                SELECT cf.CAPABILITY_INSTANCE_ID,
                       cf.CAPABILITY_INSTANCE_NAME,
                       cf.CAPABILITY_INSTANCE_DESCRIPTION,
                       cf.CAPABILITY_ID,
                       cf.DISPLAY_NAME,
                       cf.CAPABILITY_TYPE,
                       cf.namespace,
                       cf.VERSION, cf.STATUS, cf.REGION, cf.TAGS,
                       cf.MODIFIED_TIME, cf.MONITORING_STATUS
            ) AS ColumnName (
                CAPABILITY_INSTANCE_ID, CAPABILITY_INSTANCE_NAME, CAPABILITY_INSTANCE_DESCRIPTION,
                CAPABILITY_ID, CAPABILITY_NAME, CAPABILITY_TYPE, NAMESPACE,
                VERSION, STATUS, REGION, TAGS, MODIFIED_TIME, MONITORING_STATUS
            )
        ))) AS CAPABILITIES
    FROM   ci_flat cf
    GROUP  BY cf.DP_ID
),
app_agg AS (
    SELECT DP_ID,
           json_agg(row_to_json((
               SELECT ColumnName
               FROM (SELECT A.APP_ID, A.APP_NAME, A.APP_VERSION,
                            A.CAPABILITY_INSTANCE_ID, A.CAPABILITY_ID,
                            A.CAPABILITY_VERSION, A.STATE, A.TAGS, A.MODIFIED_TIME)
                    AS ColumnName (APP_ID, APP_NAME, APP_VERSION,
                                   CAPABILITY_INSTANCE_ID, CAPABILITY_ID,
                                   CAPABILITY_VERSION, STATE, TAGS, MODIFIED_TIME)
           ))) AS APPS
    FROM   V3_APPS A
    GROUP  BY DP_ID
)
SELECT
    DP.SUBSCRIPTION_ID,
    DP.DP_ID,
    DP.NAME,
    DP.DESCRIPTION,
    DP.HOST_CLOUD_TYPE,
    DP.DP_CONFIG,
    DP.STATUS,
    DP.MONITORING_STATUS,
    DP.REGISTERED_REGION,
    DP.RUNNING_REGION,
    DP.MODIFIED_DATE,
    DP.TAGS,
    DP.CONTAINER_REGISTRY_CREDENTIAL,
    DP.CONNECTION_DETAILS,
    COALESCE(dn.namespaces, ARRAY[]::TEXT[]) AS NAMESPACES,
    ci_agg.CAPABILITIES,
    app_agg.APPS,
    RI.RESOURCE_INSTANCE_METADATA
FROM  V3_DATA_PLANES DP
LEFT  JOIN dp_ns    dn    ON dn.dp_id     = DP.DP_ID
LEFT  JOIN ci_agg         ON ci_agg.DP_ID = DP.DP_ID
LEFT  JOIN app_agg        ON app_agg.DP_ID = DP.DP_ID
LEFT  JOIN V3_RESOURCE_INSTANCES RI
          ON RI.SCOPE          = 'DATAPLANE'
         AND RI.SCOPE_ID       = DP.DP_ID
         AND RI.RESOURCE_ID    = 'SERVICEACCOUNT'
         AND RI.RESOURCE_LEVEL = 'INFRA'
WITH DATA;

CREATE UNIQUE INDEX VIEW_DATA_PLANE_CAPABILITY_INSTANCE_INDEX
    ON V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES (DP_ID);

DROP TRIGGER IF EXISTS V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES_DP_TRIGGER ON V3_DATA_PLANES;
CREATE TRIGGER V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES_DP_TRIGGER AFTER
    INSERT OR DELETE OR UPDATE OF SUBSCRIPTION_ID, DP_ID, NAME, DESCRIPTION,
                                  HOST_CLOUD_TYPE, DP_CONFIG, STATUS,
                                  REGISTERED_REGION, RUNNING_REGION,
                                  MODIFIED_DATE, TAGS,
                                  CONTAINER_REGISTRY_CREDENTIAL,
                                  CONNECTION_DETAILS, RESOURCE_INSTANCE_IDS
    ON V3_DATA_PLANES
    FOR EACH STATEMENT EXECUTE PROCEDURE V3_VIEW_DATA_PLANE_CAPABILITY_INSTANCES_REFRESH();

-- ============================================================================
-- PHASE 2c (PCP-20891): Recreate notify_dp_namespaces_change stub function and
--   its trigger on V3_DATA_PLANES. Function body matches the 21-up.sql:146
--   stub (no-op); the pre-PCP-10813 body that read OLD/NEW.namespaces is NOT
--   restored — that behavior was superseded by the RI-based notifications in
--   21-up.sql:865-941.
-- ============================================================================

CREATE OR REPLACE FUNCTION notify_dp_namespaces_change()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_dp_namespaces_change ON V3_DATA_PLANES;
CREATE TRIGGER notify_dp_namespaces_change
    AFTER INSERT OR UPDATE OR DELETE
    ON V3_DATA_PLANES
    FOR EACH ROW
    EXECUTE FUNCTION notify_dp_namespaces_change();

-- ============================================================================
-- PHASE 3: Recreate the two materialized views that 22-up dropped, using their
--          last (18-up.sql) definitions. V3_VIEW_RESOURCE_INSTANCE_LINKED_ENTITIES
--          had replaced both of them.
-- ============================================================================

-- 3a. V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES
DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES CASCADE;

CREATE MATERIALIZED VIEW V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES AS
SELECT
    RI.RESOURCE_INSTANCE_ID,
    RI.RESOURCE_ID,
    RI.RESOURCE_INSTANCE_NAME,
    RI.RESOURCE_INSTANCE_DESCRIPTION,
    RI.SCOPE,
    RI.SCOPE_ID AS SUBSCRIPTION_ID,
    RI.REGION,
    RI.RESOURCE_INSTANCE_METADATA,
    RI.CREATED_BY,
    RI.MODIFIED_BY,
    RI.CREATED_TIME,
    RI.MODIFIED_TIME,
    RI.RESOURCE_LEVEL,
    RI.CAPABILITY_ID,
    RI.RESOURCE_TYPE,
    COALESCE(
            JSON_AGG(
                    JSON_BUILD_OBJECT('id', DP.DP_ID, 'name', DP.NAME)
            ) FILTER (WHERE DP.DP_ID IS NOT NULL),
            '[]'::JSON
    ) AS LINKED_DATAPLANES
FROM V3_RESOURCE_INSTANCES RI
LEFT JOIN V3_DATA_PLANES DP ON RI.SCOPE_ID = DP.SUBSCRIPTION_ID
    AND RI.RESOURCE_INSTANCE_ID = ANY(DP.RESOURCE_INSTANCE_IDS)
WHERE RI.SCOPE = 'SUBSCRIPTION'
GROUP BY
    RI.RESOURCE_INSTANCE_ID,
    RI.RESOURCE_ID,
    RI.RESOURCE_INSTANCE_NAME,
    RI.RESOURCE_INSTANCE_DESCRIPTION,
    RI.SCOPE,
    RI.SCOPE_ID,
    RI.REGION,
    RI.RESOURCE_INSTANCE_METADATA,
    RI.CREATED_BY,
    RI.MODIFIED_BY,
    RI.CREATED_TIME,
    RI.MODIFIED_TIME,
    RI.RESOURCE_LEVEL,
    RI.CAPABILITY_ID,
    RI.RESOURCE_TYPE
WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_INDEX ON V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES
    (RESOURCE_INSTANCE_ID,RESOURCE_ID,SUBSCRIPTION_ID);

DROP FUNCTION IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_REFRESH() CASCADE;
CREATE FUNCTION V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_REFRESH()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES;
RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_RI_TRIGGER ON V3_RESOURCE_INSTANCES;
CREATE TRIGGER V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_RI_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
              ON V3_RESOURCE_INSTANCES
                  FOR EACH STATEMENT
                  EXECUTE PROCEDURE V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_REFRESH();

DROP TRIGGER IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_DP_TRIGGER ON V3_DATA_PLANES;
CREATE TRIGGER V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_DP_TRIGGER
    AFTER INSERT OR UPDATE OR DELETE
                    ON V3_DATA_PLANES
                        FOR EACH STATEMENT
                        EXECUTE PROCEDURE V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_DATAPLANES_REFRESH();

-- 3b. V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES
DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES CASCADE;

CREATE MATERIALIZED VIEW V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES AS
SELECT
    RI.RESOURCE_INSTANCE_ID,
    RI.RESOURCE_ID,
    RI.RESOURCE_INSTANCE_NAME,
    RI.RESOURCE_INSTANCE_DESCRIPTION,
    RI.SCOPE,
    RI.SCOPE_ID AS DP_ID,
    DP.NAME AS DP_NAME,
    DP.SUBSCRIPTION_ID,
    RI.REGION,
    RI.RESOURCE_INSTANCE_METADATA,
    RI.CREATED_BY,
    RI.MODIFIED_BY,
    RI.CREATED_TIME,
    RI.MODIFIED_TIME,
    RI.RESOURCE_LEVEL,
    RI.CAPABILITY_ID,
    RI.RESOURCE_TYPE,
    COALESCE(
            JSON_AGG(
                    JSON_BUILD_OBJECT('id', CI.CAPABILITY_INSTANCE_ID, 'name', CI.CAPABILITY_INSTANCE_NAME, 'capability', CI.CAPABILITY_ID)
            ) FILTER (WHERE CI.CAPABILITY_INSTANCE_ID IS NOT NULL),
            '[]'::JSON
    ) AS LINKED_CAPABILITIES
FROM V3_RESOURCE_INSTANCES RI
         LEFT JOIN V3_DATA_PLANES DP
                   ON RI.SCOPE_ID = DP.DP_ID
         LEFT JOIN V3_CAPABILITY_INSTANCES CI
                   ON RI.SCOPE_ID = CI.DP_ID
                       AND RI.RESOURCE_INSTANCE_ID = ANY(CI.RESOURCE_INSTANCE_IDS)
WHERE RI.SCOPE = 'DATAPLANE'
GROUP BY
    RI.RESOURCE_INSTANCE_ID,
    RI.RESOURCE_ID,
    RI.RESOURCE_INSTANCE_NAME,
    RI.RESOURCE_INSTANCE_DESCRIPTION,
    RI.SCOPE,
    RI.SCOPE_ID,
    DP.NAME,
    DP.SUBSCRIPTION_ID,
    RI.REGION,
    RI.RESOURCE_INSTANCE_METADATA,
    RI.CREATED_BY,
    RI.MODIFIED_BY,
    RI.CREATED_TIME,
    RI.MODIFIED_TIME,
    RI.RESOURCE_LEVEL,
    RI.CAPABILITY_ID,
    RI.RESOURCE_TYPE
    WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_INDEX ON V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES
    (RESOURCE_INSTANCE_ID,RESOURCE_ID,DP_ID,SUBSCRIPTION_ID);

DROP FUNCTION IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_REFRESH() CASCADE;
CREATE FUNCTION V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_REFRESH()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES;
RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_RI_TRIGGER ON V3_RESOURCE_INSTANCES;
CREATE TRIGGER V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_RI_TRIGGER AFTER
    INSERT OR UPDATE OR DELETE
              ON V3_RESOURCE_INSTANCES
                  FOR EACH STATEMENT
                  EXECUTE PROCEDURE V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_REFRESH();

DROP TRIGGER IF EXISTS V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_CI_TRIGGER ON V3_CAPABILITY_INSTANCES;
CREATE TRIGGER V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_CI_TRIGGER
    AFTER INSERT OR UPDATE OR DELETE
                    ON V3_CAPABILITY_INSTANCES
                        FOR EACH STATEMENT
                        EXECUTE PROCEDURE V3_VIEW_RESOURCE_INSTANCE_WITH_LINKED_CAPABILITIES_REFRESH();

-- ============================================================================
-- PHASE 4: Remove seed/reference data inserted in 22-up
--   These DELETEs will fail if the rows are referenced by capability instances;
--   that is the correct safety behavior - remove the dependents first, then re-run.
-- ============================================================================

-- PCP-19083 : feature metadata
DELETE FROM V3_FEATURE_METADATA WHERE FEATURE_ID = 'SB';

-- PCP-15443 / PCP-18723 : capability metadata
DELETE FROM V3_CAPABILITY_METADATA WHERE CAPABILITY_ID = 'SB'  AND CAPABILITY_TYPE = 'PLATFORM';
DELETE FROM V3_CAPABILITY_METADATA WHERE CAPABILITY_ID = 'AS'  AND CAPABILITY_TYPE = 'PLATFORM';
DELETE FROM V3_CAPABILITY_METADATA WHERE CAPABILITY_ID = 'FTL' AND CAPABILITY_TYPE = 'PLATFORM';
-- PCP-20465 : Infra MCP Server capability metadata
DELETE FROM V3_CAPABILITY_METADATA WHERE CAPABILITY_ID = 'INFRAMCPSERVER' AND CAPABILITY_TYPE = 'PLATFORM';

-- ============================================================================
-- PHASE 5: Restore schema version back to 21 (1.18.0)
-- ============================================================================
UPDATE schema_version SET version = 21;
