-- Database schema changes for 1.6.0

-- PCP-10854: Upgrade Orchestrator API to accept externalAccountId and soft_limit while updating a subscription settings
-- Need to drop and recreate V3_VIEW_USER_ACCOUNT_SUBSCRIPTION_DATA_PLANES since we are adding two more fields : soft_limit and external_account_id
DROP MATERIALIZED VIEW IF EXISTS V3_VIEW_USER_ACCOUNT_SUBSCRIPTION_DATA_PLANES CASCADE;

-- Now recreate V3_VIEW_USER_ACCOUNT_SUBSCRIPTION_DATA_PLANES
CREATE MATERIALIZED VIEW V3_VIEW_USER_ACCOUNT_SUBSCRIPTION_DATA_PLANES
AS
SELECT
    U.EMAIL,
    U.FIRSTNAME,
    U.LASTNAME,
    A.DISPLAY_NAME,
    A.HOST_PREFIX,
    A.CREATED_TIME,
    A.ACCOUNT_SETTINGS -> 'ownerLimit' as owner_limit,
    A.ACCOUNT_SETTINGS -> 'softLimit' as soft_limit,
    A.ACCOUNT_SETTINGS -> 'externalAccountId' as external_account_id,
    A.comment as ACCOUNT_COMMENT,
    S.SUBSCRIPTION_ID,
    S.EXTERNAL_SUBSCRIPTION_ID,
    S.TSC_ACCOUNT_ID,
    S.SUBSCRIPTION_TYPE,
    S.START_OF_CONTRACT_TIME,
    S.END_OF_CONTRACT_TIME,
    S.STATUS,
    (SELECT count(*) from v3_data_planes where subscription_id = S.subscription_id) as DP_COUNT,
    (SELECT coalesce(v2arq.soft_limit, v2r.soft_limit)) as dp_soft_limit,
    DP.DATA_PLANES
FROM ((
    V2_SUBSCRIPTIONS S
        LEFT JOIN (
        SELECT SUBSCRIPTION_ID, json_agg(row_to_json((
            SELECT ColumnName
            FROM (SELECT DP_ID, NAME, DESCRIPTION, HOST_CLOUD_TYPE, STATUS, REGISTERED_REGION,RUNNING_REGION,CREATED_DATE,MODIFIED_DATE,CREATED_BY,MODIFIED_BY,TAGS,NAMESPACES,RESOURCE_INSTANCE_IDS,DP_CONFIG,EULA)
                     AS ColumnName (DP_ID, NAME, DESCRIPTION, HOST_CLOUD_TYPE, STATUS,REGISTERED_REGION,RUNNING_REGION,CREATED_DATE,MODIFIED_DATE,CREATED_BY,MODIFIED_BY,TAGS,NAMESPACES,RESOURCE_INSTANCE_IDS,DP_CONFIG,EULA)
        ))) DATA_PLANES
        FROM V3_DATA_PLANES
        GROUP BY SUBSCRIPTION_ID) DP USING (SUBSCRIPTION_ID)
    ))
         LEFT JOIN V2_USERS U ON U.USER_ENTITY_ID=S.CREATED_FOR
         LEFT JOIN V2_ACCOUNTS A ON A.TSC_ACCOUNT_ID = S.TSC_ACCOUNT_ID
         LEFT JOIN V2_RESOURCES v2r ON v2r.RESOURCE_NAME = 'DATA_PLANE_COUNT'
         LEFT JOIN V2_ACCOUNTS_RESOURCES_QUOTA v2arq ON v2r.id = v2arq.id AND v2arq.TSC_ACCOUNT_ID = S.TSC_ACCOUNT_ID
    WITH DATA;

CREATE UNIQUE INDEX V3_VIEW_USER_ACCOUNT_SUBSCRIPTION_DATA_PLANES_INDEX ON V3_VIEW_USER_ACCOUNT_SUBSCRIPTION_DATA_PLANES (SUBSCRIPTION_ID);

-- Update database schema at the end (earlier version is 1.5.1 i.e. 8)
UPDATE schema_version SET version = 9;
