# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
appVersion: "1.18.0"
dependencies:
- condition: global.tibco.hybridConnectivity.enabled
  name: tp-tibtunnel
  repository: ""
  version: 1.18.*
- condition: tp-provisioner-agent.enabled
  name: tp-provisioner-agent
  repository: ""
  version: 1.18.*
description: A Helm chart for Data Plane Infrastructure
name: dp-core-infrastructure
type: application
version: 1.18.4
