# Copyright © 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

# Default values for flogoprovisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  cp:
    dataplaneId: dp-dp1
    instanceId: defaultinstid
    cpCertificateSecret: ""
    cpHostname: "acme.local.my.cic2.pro"
    dpUrl:
      host: "dp-{{ $.Values.global.cp.dataplaneId }}.platform.local"
      port: 443
    containerRegistry:
      secret: ""
      url: ""
      repository: "tibco-platform-docker-prod"
    environmentType: ""
    enableResourceConstraints: true
    resources:
      serviceaccount:
        namespace: ""
        serviceAccountName: ""
      ingress:
        fqdn: ""
        ingressClassName: ""
        ingressController: ""
        annotations: {}
      gatewayapi:
        gatewayAPIControllerName: ""
        gatewayName: ""
        gatewayNamespace: ""
        gatewayHostOrDomainName: ""
        gatewaySectionName: ""
      activationServer:
        url: ""
    secrets:
      # iat : Control Plane Authentication
      # this is used to generate client id and client secret.
      # Client Id and secret are used to generate time bound access token
      iat: ""  # initial access token used to generate client credentials

    # proxy configuration for the outward traffic from cp proxy
    # should have access to the proxy server and proxy server should have access to CP Subscription DNS domain
    proxy:
      # http proxy to forward the http traffic. Ex : http://proxy.example.com:8080
      httpProxy: ""
      # https proxy to forward the https traffic. Ex: https://proxy.example.com:8080
      httpsProxy: ""
      # comma separated list of domains to exclude from proxy. Ex: .example1.com,.example2.com
      noProxy: ""

    logging:
      # The fluentbit configuration section.
      # It specifies that the fluentbit should not run as a non-root user and the user ID should be 0 (root).
      # Privilege escalation is not allowed for security reasons.
      # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
      # GitHub issue: https://github.com/fluent/fluent-bit/issues/872#issuecomment-827763207, https://github.com/kyma-project/kyma/pull/11657/files
      fluentbit:
        enabled: true
        apps:
          enabled: true
        image:
          tag: 5.0.6
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
          limits:
            cpu: 50m
            memory: 30Mi
        probes:
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/uptime
              port: 2020
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
              - CAP_NET_RAW

  flogoprovisioner:
    serviceAccount: ""
    image:
      registry: 664529841144.dkr.ecr.us-west-2.amazonaws.com
      tag: 452
    deploymanager:
      image:
        enabled: false
        registry: ""
        tag: ""
        resources: {}

replicaCount: 1

image:
  repository: tibco-platform/tp-flogo-provisioner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

# Pod Security Context configuration
# This configuration ensures that the pod is run with non-root privileges for enhanced security.
# The user, group, and filesystem group IDs are all set to 1000.
# The filesystem group change policy is set to "Always", meaning the filesystem group is always set to the fsGroup.
# The seccomp (secure computing mode) profile is set to RuntimeDefault, which means it uses the default profile provided by the runtime.
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "Always"
  seccompProfile:
    type: RuntimeDefault

securityContext:
  # This section of the configuration is for the flogoprovisioner.
  # It specifies that privilege escalation is not allowed for security reasons.
  # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
  flogoprovisioner:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
        - CAP_NET_RAW
  infraCPProxy:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

service:
  type: ClusterIP
  port: 7814
  targetPort: 7814

publicApiService:
  type: ClusterIP
  port: 7816
  targetPort: 7816

ingress:
  # -- Enables configuration of ingress to expose flogoprovisioner. Requires ingress support in the Kubernetes cluster.
  enabled: true
  hostsOverride: false
  className: haproxy
  hosts:
    - host: "placeholder"
      paths:
        - path: /
          pathType: Prefix
  # -- Annotations for the ingress object. See documentation for your ingress controller for valid annotations.
  annotations:
    haproxy.org/cors-enable: "true"
    haproxy.org/load-balance: leastconn
    haproxy.org/src-ip-header: X-Real-IP
    # haproxy.org/timeout-http-request: 600s

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: "2"
    memory: 2Gi
  limits:
    cpu: "4"
    memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 10
    periodSeconds: 10
    timeoutSeconds: 10

# -- Additional environment variables.
extraEnvVars: []
#  - name: NAME
#    value: value

# The name of ConfigMap containing additional environment variables.
extraEnvVarsCM: ""

# The name of Secret containing extra additional environment variables.
extraEnvVarsSecret: ""

# -- Extra volumeMounts for the integration services container.
# More info: `kubectl explain deployment.spec.template.spec.containers.volumeMounts`.
extraVolumeMounts: []
  # - name: example
  #   mountPath: /opt/tibco/example.txt
#   subPath: example.txt

# -- Extra volumes for the integration services container.
# More info: `kubectl explain deployment.spec.template.spec.volumes`.
extraVolumes: []
  # - name: example
  #   persistentVolumeClaim:
#     claimName: exampleClaim

# -- Additional init containers to add to the automationservices pod.
extraInitContainers: []
  # - name: dummy-init
  #   image: busybox
  #   command: ['echo', "hey"]

config:
  ARTIFACT_MANAGER_PORT: "7813"
  APP_INIT_IMAGE_TAG: "31"
  INFRA_CP_PROXY_IMAGE_TAG: "280"

publicApi:
  config:
    pathPrefix: /tibco/flogo
  gke:
    healthCheckPolicy:
      default:
        checkIntervalSec: 20
        timeoutSec: 10
        healthyThreshold: 1
        unhealthyThreshold: 3
        config:
          type: HTTP
          httpHealthCheck:
            port: 7814
            requestPath: /v1/liveness

infraCPProxy:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

fluentbit:
  apps:
    config:
      fluentbit: |-
        [SERVICE]
          Flush           1
          Daemon          off
          Log_Level       error
          Parsers_File    parsers.conf
          HTTP_Server     On
          HTTP_Listen     0.0.0.0
          HTTP_Port       2020
          Health_Check    On

        @INCLUDE input-tail.conf
        @INCLUDE output-otel.conf
        @INCLUDE filters.conf

      filters: |-
        [FILTER]
          Name   parser
          Match  app.*
          key_name log
          parser  formattedlog
          parser  unformattedlog

        [FILTER]
          Name   lua
          Match  app.*
          Script update_record.lua
          Call   update_record

      parsers: |-
        [MULTILINE_PARSER]
          name          multiline-regex
          type          regex
          key_content   log
          flush_timeout 1000
          rule          "start_state"   "/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)\s+(INFO|WARN|DEBUG|ERROR|FATAL)\s+.*/"     "cont"
          rule          "cont"          "/^(?!\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z\s+(INFO|WARN|DEBUG|ERROR|FATAL)\s+).*/"   "cont"

        [PARSER]
          Name        formattedlog
          Format      regex
          Regex       /^(?<log_time>[^ ]*)\t(?<log_level>INFO|WARN|DEBUG|ERROR|FATAL)\t(?<message>.*)/m
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
          Time_Keep   On

        [PARSER]
          Name        unformattedlog
          Format      regex
          Regex       /^(?<message>.*)/m
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
          Time_Keep   On

      inputtail: |-
        [INPUT]
          Name              tail
          Tag               app.*
          Path              /var/log/pods/*${POD_NAME}*/${CONTAINER_NAME}/*.log
          multiline.parser  docker, cri, multiline-regex
          Mem_Buf_Limit     30MB
          Read_From_Head    True
          Buffer_Chunk_Size 10M
          Buffer_Max_Size   20M
          skip_long_lines   Off

      outputotel: |-
        [OUTPUT]
          Name                 opentelemetry
          Match                app.*
          Host                 otel-userapp-logs
          Port                 4318
          Log_response_payload True
          Logs_body_key        $log
          Tls                  Off
          Tls.verify           Off

      updaterecordlua: |-
        function update_record(tag, timestamp, record)
          msg = record["message"]
          if msg ~= nil then
            trace_id = msg:match("%[traceID:%s*([%da-fA-F]+)%]")
            span_id = msg:match("%[spanID:%s*([%da-fA-F]+)%]")
            if trace_id then
              record["trace_id"] = trace_id
            end
            if span_id then
              record["span_id"] = span_id
            end
            if msg:find("%[flogo%.general%.activity%.log%]") then
              record["log_type"] = "user"
            else
              record["log_type"] = "engine"
            end
            return 1, timestamp, record
          end
          return 1, timestamp, record
        end
