
CREATE TABLE if not exists TCTA_SUB (
  TSC_SUB_ID varchar(255) NOT NULL,
  SUB_SEATS varchar(255) NOT NULL,
  SUB_CAPACITY varchar(255) NOT NULL,
  STATUS varchar(255) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL,
  UPDATE_TS timestamp NOT NULL,
  PRIMARY KEY (TSC_SUB_ID)
);

CREATE TABLE if not exists TCTA_TSC_USER (
  TSC_USER_ID varchar(255) NOT NULL,
  FIRST_NAME varchar(255) DEFAULT NULL,
  LAST_NAME varchar(255) DEFAULT NULL,
  ROLE_LIST varchar(255) NOT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL,
  UPDATE_TS timestamp NOT NULL,
  PRIMARY KEY (TSC_USER_ID)
);

CREATE TABLE if not exists TCTA_USER (
  USER_ID varchar(255) NOT NULL,
  TSC_SUB_ID varchar(255) NOT NULL,
  TSC_USER_ID varchar(255) NOT NULL,
  SECRET_ID varchar(255) DEFAULT NULL,
  PRIMARY KEY (USER_ID),
  CONSTRAINT fk_sub_plan_id FOREIGN KEY (TSC_SUB_ID) REFERENCES TCTA_SUB (TSC_SUB_ID),
  CONSTRAINT fk_tsc_user_id FOREIGN KEY (TSC_USER_ID) REFERENCES TCTA_TSC_USER (TSC_USER_ID)
 );

CREATE TABLE if not exists TCTA_USER_HISTORY (
  id        SERIAL PRIMARY KEY,
  USER_ID varchar(255) NOT NULL,
  LOGIN_TS timestamp NOT NULL,
  LOGOUT_TS timestamp NOT NULL,
  TERMINATE_TS timestamp NOT NULL
);


CREATE TABLE if not exists TCTA_USER_QUOTA (
  TSC_SUB_ID varchar(255) NOT NULL,
  MAX_DAILY_TXN integer DEFAULT 500,
  MAX_STORAGE integer DEFAULT 5,
  CREATE_TS timestamp NOT NULL,
  UPDATE_TS timestamp NOT NULL,
  PRIMARY KEY (TSC_SUB_ID)
);

CREATE TABLE if not exists TCTA_ERROR_QUEUE (
   id        SERIAL PRIMARY KEY,
  USER_ID varchar(255) NOT NULL,
  ERROR_MESSAGE varchar(512) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL,
  UPDATE_TS timestamp NOT NULL
);


CREATE TABLE if not exists TCTA_ROLE (
  ROLE_ID varchar(255) NOT NULL,
  ROLE_NAME varchar(255) DEFAULT NULL,
  COMPONENT_LIST varchar(512) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL,
  UPDATE_TS timestamp NOT NULL,
  PRIMARY KEY (ROLE_ID)
);

CREATE TABLE if not exists TCTA_COMPONENT (
  COMPONENT_ID varchar(255) NOT NULL,
  COMPONENT_NAME varchar(255) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL,
  UPDATE_TS timestamp NOT NULL,
  PRIMARY KEY (COMPONENT_ID)
);

CREATE TABLE if not exists SCHEMA_VERSION (ID SERIAL PRIMARY KEY, VERSION INTEGER NOT NULL);

INSERT INTO SCHEMA_VERSION  (VERSION) VALUES (1);

