-- update schema_version table
UPDATE SCHEMA_VERSION SET VERSION = 2;


-- drop all tcta tables for beta release
DROP TABLE IF EXISTS TCTA_USER;
DROP TABLE IF EXISTS TCTA_SUB;
DROP TABLE IF EXISTS TCTA_TSC_USER;
DROP TABLE IF EXISTS TCTA_USER_HISTORY;
DROP TABLE IF EXISTS TCTA_USER_QUOTA;
DROP TABLE IF EXISTS TCTA_ERROR_QUEUE;
DROP TABLE IF EXISTS TCTA_ROLE;
DROP TABLE IF EXISTS TCTA_COMPONENT;


-- recreate all tcta tables
CREATE TABLE TCTA_SUB (
    TSC_SUB_ID      VARCHAR(255) NOT NULL,
    SUB_SEATS       VARCHAR(255) NOT NULL,
    SUB_CAPACITY    VARCHAR(255) NOT NULL,
    STATUS          VARCHAR(255) DEFAULT NULL,
    CREATE_TS       TIMESTAMP NOT NULL,
    UPDATE_TS       TIMESTAMP NOT NULL,
    PRIMARY KEY (TSC_SUB_ID)
);

CREATE TABLE TCTA_TSC_USER (
    TSC_USER_ID    VARCHAR(255) NOT NULL,
    FIRST_NAME     VARCHAR(255) DEFAULT NULL,
    LAST_NAME      VARCHAR(255) DEFAULT NULL,
    ROLE_LIST      VARCHAR(255) NOT NULL,
    EMAIL          VARCHAR(255) DEFAULT NULL,
    CREATE_TS      TIMESTAMP NOT NULL,
    UPDATE_TS      TIMESTAMP NOT NULL,
    PRIMARY KEY (TSC_USER_ID)
);

CREATE TABLE TCTA_USER (
    USER_ID        VARCHAR(255) NOT NULL,
    TSC_SUB_ID     VARCHAR(255) NOT NULL,
    TSC_USER_ID    VARCHAR(255) NOT NULL,
    SECRET_ID      VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (USER_ID),
    CONSTRAINT FK_SUB_PLAN_ID FOREIGN KEY (TSC_SUB_ID) REFERENCES TCTA_SUB (TSC_SUB_ID),
    CONSTRAINT FK_TSC_USER_ID FOREIGN KEY (TSC_USER_ID) REFERENCES TCTA_TSC_USER (TSC_USER_ID)
);

CREATE TABLE TCTA_USER_HISTORY (
    ID              SERIAL PRIMARY KEY,
    USER_ID         VARCHAR(255) NOT NULL,
    LOGIN_TS        TIMESTAMP NOT NULL,
    LOGOUT_TS       TIMESTAMP NOT NULL,
    TERMINATE_TS    TIMESTAMP NOT NULL
);

CREATE TABLE TCTA_USER_QUOTA (
    TSC_SUB_ID       VARCHAR(255) NOT NULL,
    MAX_DAILY_TXN    INTEGER DEFAULT 1000,
    MAX_STORAGE      INTEGER DEFAULT 5,
    CREATE_TS        TIMESTAMP NOT NULL,
    UPDATE_TS        TIMESTAMP NOT NULL,
    PRIMARY KEY (TSC_SUB_ID)
);

CREATE TABLE TCTA_ERROR_QUEUE (
    ID               SERIAL PRIMARY KEY,
    USER_ID          VARCHAR(255) NOT NULL,
    ERROR_MESSAGE    VARCHAR(512) DEFAULT NULL,
    CREATE_TS        TIMESTAMP NOT NULL,
    UPDATE_TS        TIMESTAMP NOT NULL
);

CREATE TABLE TCTA_ROLE (
    ROLE_NAME         VARCHAR(128) NOT NULL,
    COMPONENT_LIST    VARCHAR(2048) DEFAULT NULL,
    CREATE_TS         TIMESTAMP NOT NULL,
    UPDATE_TS         TIMESTAMP NOT NULL,
    PRIMARY KEY (ROLE_NAME)
);

CREATE TABLE TCTA_COMPONENT (
    COMPONENT_ID      VARCHAR(255) NOT NULL,
    COMPONENT_NAME    VARCHAR(255) DEFAULT NULL,
    CREATE_TS         TIMESTAMP NOT NULL,
    UPDATE_TS         TIMESTAMP NOT NULL,
    PRIMARY KEY (COMPONENT_ID)
);


-- initialized data
INSERT INTO TCTA_ROLE (ROLE_NAME, COMPONENT_LIST, CREATE_TS, UPDATE_TS) VALUES 
('ADM', '[{"component": "ui.home", "permission": "RW"},
{"component": "ui.transactions", "permission": "RW" },
{"component": "ui.connectors", "permission": "RW" },
{"component": "ui.settings", "permission": "RW" }]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TCTA_ROLE (ROLE_NAME, COMPONENT_LIST, CREATE_TS, UPDATE_TS) VALUES 
('USR', '[{"component": "ui.home", "permission": "RW"},
{"component": "ui.transactions", "permission": "RW" },
{"component": "ui.connectors", "permission": "NONE" },
{"component": "ui.settings", "permission": "NONE" }]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
