-- create "uuid-ossp" extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- create function to update column UPDATE_TS
-- DROP FUNCTION IF EXISTS UPDATE_TIMESTAMP_FOR_CHANGE();

CREATE OR REPLACE FUNCTION UPDATE_TIMESTAMP_FOR_CHANGE()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATE_TS = now();
    RETURN NEW;
END;
$$ language 'plpgsql';


-- create table TCTA_STATUS
CREATE TABLE TCTA_STATUS(
    STATUS_ID       UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    STATUS_NAME     CHARACTER VARYING(128) NOT NULL,
    STATUS_DESP     CHARACTER VARYING(128),
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX UNQ_STATUSNAME_SUBID ON TCTA_STATUS (lower(STATUS_NAME), TSC_SUB_ID);

CREATE INDEX TCTA_STATUS_IDX ON TCTA_STATUS (TSC_SUB_ID);

CREATE TRIGGER TCTA_STATUS_UPDATE_TS BEFORE UPDATE
    ON TCTA_STATUS FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_STATE
CREATE TABLE TCTA_STATE(
    STATE_ID        UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    STATE_NAME      CHARACTER VARYING(128) NOT NULL,
    STATE_DESP      CHARACTER VARYING(128),
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX UNQ_STATENAME_SUBID ON TCTA_STATE (lower(STATE_NAME), TSC_SUB_ID);

CREATE INDEX TCTA_STATE_IDX ON TCTA_STATE (TSC_SUB_ID);

CREATE TRIGGER TCTA_STATE_UPDATE_TS BEFORE UPDATE
    ON TCTA_STATE FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_PROPERTY
CREATE TABLE TCTA_PROPERTY(
    PROP_KEY        CHARACTER VARYING(128) NOT NULL PRIMARY KEY,
    PROP_TYPE       CHARACTER VARYING(32) NOT NULL,
    PROP_NAME       CHARACTER VARYING(128) NOT NULL,
    PROP_DESP       CHARACTER VARYING(512) NOT NULL,
    DEFAULT_VAL     CHARACTER VARYING(128) NOT NULL,
    IS_HIDDEN       BOOLEAN NOT NULL DEFAULT FALSE
);


-- create table TCTA_SETTING
CREATE TABLE TCTA_SETTING(
    PROP_ID         UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    PROP_KEY        CHARACTER VARYING(128) NOT NULL,
    PROP_VALUE      CHARACTER VARYING(128) NOT NULL,
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX TCTA_SETTING_IDX ON TCTA_SETTING (TSC_SUB_ID);

CREATE TRIGGER TCTA_SETTING_UPDATE_TS BEFORE UPDATE
    ON TCTA_SETTING FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_UI_COLUMN
CREATE TABLE TCTA_UI_COLUMN(
    COL_NAME            CHARACTER VARYING(64) NOT NULL PRIMARY KEY,
    IS_SEARCHABLE       BOOLEAN NOT NULL,
    IS_VISIBLE          BOOLEAN NOT NULL,
    IS_MAIN_PAGE_COL    BOOLEAN NOT NULL,
    DISPLAY_NAME        CHARACTER VARYING(128) NOT NULL
);


-- create table TCTA_COLUMN_VISIBILITY
CREATE TABLE TCTA_COLUMN_VISIBILITY(
    USER_ID         UUID NOT NULL,
    COL_NAME        CHARACTER VARYING(64) NOT NULL,
    IS_VISIBLE      BOOLEAN NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (USER_ID, COL_NAME)
);

CREATE TRIGGER TCTA_COLUMN_VISIBILITY_UPDATE_TS BEFORE UPDATE
    ON TCTA_COLUMN_VISIBILITY FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_SEARCH_HISTORY
CREATE TABLE TCTA_SEARCH_HISTORY(
    CRITERIA_ID     UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    USER_ID         UUID NOT NULL,
    COL_NAME        CHARACTER VARYING(128) NOT NULL,
    COL_OPERATION   CHARACTER VARYING(128) NOT NULL,
    COL_VALUE       CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TRIGGER TCTA_SEARCH_HISTORY_UPDATE_TS BEFORE UPDATE
    ON TCTA_SEARCH_HISTORY FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();

CREATE INDEX TCTA_SEARCH_HISTORY_IDX ON TCTA_SEARCH_HISTORY (USER_ID);

-- create table TCTA_TRANSACTION
-- Note: the operation of dropping parent partition table also drop all partition tables
CREATE TABLE TCTA_TRANSACTION(
    TRANS_ID            UUID NOT NULL DEFAULT uuid_generate_v4(),
    USER_ID             UUID,
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    USER_TRANS_ID       CHARACTER VARYING(128) NOT NULL,
    TRANS_SOURCE        CHARACTER VARYING(128),
    TRANS_DESTINATION   CHARACTER VARYING(128),
    SERVICE_NAME        CHARACTER VARYING(128) NOT NULL,
    TRANS_TS            TIMESTAMP WITH TIME ZONE NOT NULL,
    TRANS_STATUS        CHARACTER VARYING(128),
    TRANS_STATE         CHARACTER VARYING(128),
    ENTRY_ID            CHARACTER VARYING(128),
    PARENT_ID           CHARACTER VARYING(128),
    TRANS_DESP          CHARACTER VARYING(512) NOT NULL,
    EXTRA_PROPS         JSONB,
    BC_TRANS_HASH       CHARACTER VARYING(128),
    BC_TRANS_ID         CHARACTER VARYING(128),
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
) PARTITION BY LIST (TSC_SUB_ID);


-- create table TCTA_TRANSACTION_PAYLOAD
CREATE TABLE TCTA_TRANSACTION_PAYLOAD(
    PAYLOAD_ID          UUID NOT NULL DEFAULT uuid_generate_v4(),
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    TRANS_ID            UUID NOT NULL,
    PAYLOAD_VALUE       BYTEA NOT NULL,
    IS_ENCRYPTED        BOOLEAN NOT NULL DEFAULT TRUE,
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
) PARTITION BY LIST (TSC_SUB_ID);


-- create table TCTA_AUDIT_LIMIT
CREATE TABLE TCTA_AUDIT_LIMIT(
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    TRANSACTION_COUNT   BIGINT NOT NULL,
    SUBSCRIPTION_ID     CHARACTER VARYING(128) NOT NULL,
    TRANSACTION_SIZE    BIGINT NOT NULL,
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TSC_SUB_ID)
);

CREATE TRIGGER TCTA_AUDIT_LIMIT_UPDATE_TS BEFORE UPDATE
    ON TCTA_AUDIT_LIMIT FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();

-- end of create_tables.sql ------

CREATE TABLE SCHEMA_VERSION (ID SERIAL PRIMARY KEY, VERSION INTEGER NOT NULL);

INSERT INTO SCHEMA_VERSION  (VERSION) VALUES (1);


-- initialized data for TCTA_PROPERTY
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.blockChain', 'boolean',
                                'BlockChain Verification',
                                'Enable BlockChain verification means that AuditSafe will generate hash for the transaction and save the hash into BlockChain ledger',
                                'false', false);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.payload.encryption', 'boolean',
                                'Payload Encryption',
                                'Whether encrypt Payload of audit data.',
                                'true', true);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.status.checking', 'boolean',
                                'Checking Event Status', 
                                'By enabling this property, TAS will verify the value of event_status when receiving request from post transaction API. Change of this property needs at most 30 seconds to take effect.',
                                'true', true);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.state.checking', 'boolean',
                                'Checking Audit Event', 
                                'By enabling this property, TAS will verify the value of audit_event when receiving request from post transaction API. Change of this property needs at most 30 seconds to take effect.',
                                'true', true);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.page.row.number', 'integer',
                                'Row Number',
                                'The number of rows per page.',
                                '20', true);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.blockChain.backup.url', 'string',
                                'Backup BlockChain URL for Test',
                                'The base URL of BlockChain Service for Test',
                                'https://auditsafe.blocklayer.sandbox.cloud.tibco.com/v1', true);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.blockChain.prod.backup.url', 'string',
                                'Backup BlockChain URL',
                                'The base URL of BlockChain Service',
                                'https://auditsafe.blocklayer.cloud.tibco.com/v1', true);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.log.level', 'string',
                                'Log Level of Data Server',
                                'The trace log level of data server, value list: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE and ALL. Default value is ERROR',
                                'ERROR', true);
INSERT INTO TCTA_PROPERTY VALUES ('tcta.webServer.log.level', 'string',
                                'Log Level of Web Server',
                                'The trace log level of web server, value list: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE and ALL. Default value is ERROR',
                                'ERROR', true);

-- initialized data for TCTA_UI_COLUMN
INSERT INTO TCTA_UI_COLUMN VALUES ('service_name', true, true, true, 'Business Process');
INSERT INTO TCTA_UI_COLUMN VALUES ('user_trans_id', true, true, true, 'Transaction ID');
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_state', true, true, true, 'Audit Event');
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_status', true, true, true, 'Status');
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_source', true, true, true, 'Source');
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_destination', true, true, true, 'Destination');
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_ts', true, true, true, 'Time');
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_desp', false, false, false, 'Description');
INSERT INTO TCTA_UI_COLUMN VALUES ('extra_props', false, false, false, 'Extra Information');


-- create demo data

-- create partition table for demo data
CREATE TABLE TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF PARTITION OF TCTA_TRANSACTION(
    CONSTRAINT TCTA_TRANSACTION_pkey_01CJSXXD5892QYJVR4R91384TF PRIMARY KEY (TRANS_ID)
) FOR VALUES IN ('01CJSXXD5892QYJVR4R91384TF');
--:
CREATE INDEX TCTA_TRANSACTION_IDX1_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_TS);
--:
CREATE INDEX TCTA_TRANSACTION_IDX2_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (USER_TRANS_ID);
--:
CREATE INDEX TCTA_TRANSACTION_IDX3_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_SOURCE);
--:
CREATE INDEX TCTA_TRANSACTION_IDX4_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_DESTINATION);
--:
CREATE INDEX TCTA_TRANSACTION_IDX5_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (SERVICE_NAME);
--:
CREATE INDEX TCTA_TRANSACTION_IDX6_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_STATUS);
--:
CREATE INDEX TCTA_TRANSACTION_IDX7_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_STATE);
--:
-- create partition table for TCTA_TRANSACTION_PAYLOAD
CREATE TABLE TCTA_TRANSACTION_PAYLOAD_01CJSXXD5892QYJVR4R91384TF PARTITION OF TCTA_TRANSACTION_PAYLOAD(
    CONSTRAINT TCTA_TRANS_PAYLOAD_pkey_01CJSXXD5892QYJVR4R91384TF PRIMARY KEY (PAYLOAD_ID),
    CONSTRAINT TCTA_TRANS_PAYLOAD_fkey_01CJSXXD5892QYJVR4R91384TF FOREIGN KEY (TRANS_ID)
    REFERENCES TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_ID)
) FOR VALUES IN ('01CJSXXD5892QYJVR4R91384TF');

--:

CREATE INDEX TCTA_TRANS_PAYLOAD_IDX_01CJSXXD5892QYJVR4R91384TF
	ON TCTA_TRANSACTION_PAYLOAD_01CJSXXD5892QYJVR4R91384TF (TRANS_ID);
--:

-- insert demo data

--First user sample data

--State definitions for the user
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('PO RECEIPT', 'Purchase Order received', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('CREDIT CHECK', 'Credit Check is performed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('ORDER CREATION', 'Credit Check is passed, wholesale order is placed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('INVENTORY CHECK', 'Inventory check for the placed order', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('DO CREATION', 'Delivery Orders are created', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('SHIPMENT CREATION', 'Shipments are created', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('DELIVERY', 'Shipments are complete', '01CJSXXD5892QYJVR4R91384TF');

--Status definitions for the user
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('CREATED', 'PO received', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('OPENED', 'OPENED', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('IN PROGRESS', 'processing', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('SUCCESS', 'Transaction successfully Completed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('COMPLETED', 'Transaction Completed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('FAILED', 'Transaction Rejected', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('PARTIALLY COMPLETE', 'Portion of the task is complete', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('PENDING', 'Transaction waiting on previous state to complete successfully', '01CJSXXD5892QYJVR4R91384TF');
