-- update schema_version table
UPDATE SCHEMA_VERSION SET VERSION = 2;


-- drop all tcta tables for beta release
DROP TABLE IF EXISTS TCTA_TRANSACTION_PAYLOAD;
DROP TABLE IF EXISTS TCTA_TRANSACTION;

DROP TABLE IF EXISTS TCTA_AUDIT_LIMIT;
DROP TABLE IF EXISTS TCTA_SEARCH_HISTORY;
DROP TABLE IF EXISTS TCTA_UI_COLUMN;
DROP TABLE IF EXISTS TCTA_COLUMN_VISIBILITY;
DROP TABLE IF EXISTS TCTA_SETTING;
DROP TABLE IF EXISTS TCTA_PROPERTY;
DROP TABLE IF EXISTS TCTA_STATE;
DROP TABLE IF EXISTS TCTA_STATUS;
DROP TABLE IF EXISTS TCTA_KEY_STORE;
DROP TABLE IF EXISTS TCTA_BC_POLLER_INFO;
DROP TABLE IF EXISTS TCTA_BC_POLLER_LOCK; 
DROP TABLE IF EXISTS TCTA_CAPACITY_USAGE_HISTORY;
DROP TABLE IF EXISTS TCTA_HISTORY_LOCK;

DROP FUNCTION IF EXISTS UPDATE_TIMESTAMP_FOR_CHANGE();


-- recreate all tcta tables
-- create "uuid-ossp" extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- create function to update column UPDATE_TS
-- DROP FUNCTION IF EXISTS UPDATE_TIMESTAMP_FOR_CHANGE();

CREATE OR REPLACE FUNCTION UPDATE_TIMESTAMP_FOR_CHANGE()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATE_TS = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- create table TCTA_STATUS
CREATE TABLE TCTA_STATUS(
    STATUS_ID       UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    STATUS_NAME     CHARACTER VARYING(128) NOT NULL,
    STATUS_DESP     CHARACTER VARYING(128),
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX UNQ_STATUSNAME_SUBID ON TCTA_STATUS (lower(STATUS_NAME), TSC_SUB_ID);

CREATE INDEX TCTA_STATUS_IDX ON TCTA_STATUS (TSC_SUB_ID);

CREATE TRIGGER TCTA_STATUS_UPDATE_TS BEFORE UPDATE
    ON TCTA_STATUS FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_STATE
CREATE TABLE TCTA_STATE(
    STATE_ID        UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    STATE_NAME      CHARACTER VARYING(128) NOT NULL,
    STATE_DESP      CHARACTER VARYING(128),
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX UNQ_STATENAME_SUBID ON TCTA_STATE (lower(STATE_NAME), TSC_SUB_ID);

CREATE INDEX TCTA_STATE_IDX ON TCTA_STATE (TSC_SUB_ID);

CREATE TRIGGER TCTA_STATE_UPDATE_TS BEFORE UPDATE
    ON TCTA_STATE FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_PROPERTY
CREATE TABLE TCTA_PROPERTY(
    PROP_KEY        CHARACTER VARYING(128) NOT NULL PRIMARY KEY,
    PROP_TYPE       CHARACTER VARYING(32) NOT NULL,
    PROP_NAME       CHARACTER VARYING(128) NOT NULL,
    PROP_DESP       CHARACTER VARYING(512) NOT NULL,
    DEFAULT_VAL     CHARACTER VARYING(128) NOT NULL,
    IS_HIDDEN       BOOLEAN NOT NULL DEFAULT FALSE
);


-- create table TCTA_SETTING
CREATE TABLE TCTA_SETTING(
    PROP_ID         UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    PROP_KEY        CHARACTER VARYING(128) NOT NULL,
    PROP_VALUE      CHARACTER VARYING(128) NOT NULL,
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX TCTA_SETTING_IDX ON TCTA_SETTING (TSC_SUB_ID);

CREATE TRIGGER TCTA_SETTING_UPDATE_TS BEFORE UPDATE
    ON TCTA_SETTING FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_UI_COLUMN
CREATE TABLE TCTA_UI_COLUMN(
    COL_NAME            CHARACTER VARYING(64) NOT NULL PRIMARY KEY,
    IS_SEARCHABLE       BOOLEAN NOT NULL,
    IS_VISIBLE          BOOLEAN NOT NULL,
    IS_MAIN_PAGE_COL    BOOLEAN NOT NULL,
    DISPLAY_NAME        CHARACTER VARYING(128) NOT NULL
);


-- create table TCTA_COLUMN_VISIBILITY
CREATE TABLE TCTA_COLUMN_VISIBILITY(
    USER_ID         UUID NOT NULL,
    COL_NAME        CHARACTER VARYING(64) NOT NULL,
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    IS_VISIBLE      BOOLEAN NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (USER_ID, COL_NAME)
);

CREATE TRIGGER TCTA_COLUMN_VISIBILITY_UPDATE_TS BEFORE UPDATE
    ON TCTA_COLUMN_VISIBILITY FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_SEARCH_HISTORY
CREATE TABLE TCTA_SEARCH_HISTORY(
    CRITERIA_ID     UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    USER_ID         UUID NOT NULL,
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    COL_NAME        CHARACTER VARYING(128) NOT NULL,
    COL_OPERATION   CHARACTER VARYING(128) NOT NULL,
    COL_VALUE       CHARACTER VARYING(128) NOT NULL,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TRIGGER TCTA_SEARCH_HISTORY_UPDATE_TS BEFORE UPDATE
    ON TCTA_SEARCH_HISTORY FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();

CREATE INDEX TCTA_SEARCH_HISTORY_IDX ON TCTA_SEARCH_HISTORY (USER_ID);

-- create table TCTA_TRANSACTION
-- Note: the operation of dropping parent partition table also drop all partition tables
CREATE TABLE TCTA_TRANSACTION(
    TRANS_ID            UUID NOT NULL DEFAULT uuid_generate_v4(),
    USER_ID             UUID,
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    USER_TRANS_ID       CHARACTER VARYING(128) NOT NULL,
    TRANS_SOURCE        CHARACTER VARYING(128),
    TRANS_DESTINATION   CHARACTER VARYING(128),
    SERVICE_NAME        CHARACTER VARYING(128) NOT NULL,
    TRANS_TS            TIMESTAMP WITH TIME ZONE NOT NULL,
    TRANS_STATUS        CHARACTER VARYING(128),
    TRANS_STATE         CHARACTER VARYING(128),
    ENTRY_ID            CHARACTER VARYING(128),
    PARENT_ID           CHARACTER VARYING(128),
    TRANS_DESP          CHARACTER VARYING(512) NOT NULL,
    EXTRA_PROPS         JSONB,
    BC_TRANS_HASH       CHARACTER VARYING(128),
    BC_TRANS_ID         CHARACTER VARYING(128),
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
) PARTITION BY LIST (TSC_SUB_ID);


-- create table TCTA_TRANSACTION_PAYLOAD
CREATE TABLE TCTA_TRANSACTION_PAYLOAD(
    PAYLOAD_ID          UUID NOT NULL,
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    PAYLOAD_VALUE       BYTEA NOT NULL,
    IS_ENCRYPTED        BOOLEAN NOT NULL DEFAULT TRUE,
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
) PARTITION BY LIST (TSC_SUB_ID);


-- create table TCTA_AUDIT_LIMIT
CREATE TABLE TCTA_AUDIT_LIMIT(
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    TRANSACTION_COUNT   BIGINT NOT NULL,
    TRANSACTION_SIZE    BIGINT NOT NULL,
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TSC_SUB_ID)
);

CREATE TRIGGER TCTA_AUDIT_LIMIT_UPDATE_TS BEFORE UPDATE
    ON TCTA_AUDIT_LIMIT FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_KEY_STORE
CREATE TABLE TCTA_KEY_STORE(
    CRED_ID             CHARACTER VARYING(128) NOT NULL,
    CRED_PW             CHARACTER VARYING(512),
    CRED_CONTENT        BYTEA NOT NULL,
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (CRED_ID)
);

CREATE TRIGGER TCTA_KEY_STORE_UPDATE_TS BEFORE UPDATE
    ON TCTA_KEY_STORE FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIMESTAMP_FOR_CHANGE();


-- create table TCTA_BC_POLLER_INFO
CREATE TABLE TCTA_BC_POLLER_INFO(
    TRANS_ID            UUID NOT NULL,
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    USER_TRANS_ID       CHARACTER VARYING(128) NOT NULL,
    BC_TRANS_HASH       CHARACTER VARYING(128) NOT NULL,
    CREATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TRANS_ID)
);

CREATE INDEX TCTA_BC_POLLER_INFO_IDX ON TCTA_BC_POLLER_INFO (TSC_SUB_ID);


-- create table TCTA_BC_POLLER_LOCK
CREATE TABLE TCTA_BC_POLLER_LOCK(
    TSC_SUB_ID          CHARACTER VARYING(128) NOT NULL,
    SERVER_ID           CHARACTER VARYING(128) NOT NULL,
    UPDATE_TS           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TSC_SUB_ID)
);


-- create table TCTA_CAPACITY_USAGE_HISTORY
CREATE TABLE TCTA_CAPACITY_USAGE_HISTORY(
    TSC_SUB_ID           CHARACTER VARYING(128) NOT NULL PRIMARY KEY,
    CAPACITY_DAILY_COUNT BIGINT NOT NULL,
    CAPACITY_STORAGE     BIGINT NOT NULL,
    USAGE_DAILY_COUNT    BIGINT NOT NULL,
    USAGE_STORAGE        BIGINT NOT NULL,
    CHECKED_DATE         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE TCTA_HISTORY_LOCK(
    TASK_NAME            CHARACTER VARYING(128) NOT NULL,
    UPDATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TASK_NAME)
);

-- insert init data
-- initialized data for TCTA_PROPERTY
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.blockChain', 'boolean',
                                'BlockChain Verification',
                                'Enable BlockChain verification means that AuditSafe will generate hash for the transaction and save the hash into BlockChain ledger',
                                'false', false) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.payload.encryption', 'boolean',
                                'Payload Encryption',
                                'Whether encrypt Payload of audit data.',
                                'true', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.status.checking', 'boolean',
                                'Checking Event Status', 
                                'Turn on to check if field values in the imported messages are a match for values configured in the Event Status list. For more information see the help.',
                                'false', false) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.enable.state.checking', 'boolean',
                                'Checking Audit Event', 
                                'Turn on to check if field values in the imported messages are a match for values configured in the Audit Event list. For more information see the help.',
                                'false', false) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.page.row.number', 'integer',
                                'Row Number',
                                'The number of rows per page.',
                                '50', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.blockChain.backup.url', 'string',
                                'Backup BlockChain URL for Test',
                                'The base URL of BlockChain Service for Test',
                                'https://auditsafe.blocklayer.sandbox.cloud.tibco.com/v1', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.blockChain.prod.backup.url', 'string',
                                'Backup BlockChain URL',
                                'The base URL of BlockChain Service',
                                'https://auditsafe.blocklayer.cloud.tibco.com/v1', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.log.level', 'string',
                                'Log Level of Data Server',
                                'The trace log level of data server, value list: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE and ALL. Default value is ERROR',
                                'ERROR', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.webServer.log.level', 'string',
                                'Log Level of Web Server',
                                'The trace log level of web server, value list: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE and ALL. Default value is ERROR',
                                'ERROR', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.webServer.enable.sampleData', 'boolean',
                                'Show Sample Data',
                                'By enabling this property, user can access sample data.',
                                'true', false) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.batch.post.maxItems', 'integer',
                                'Max Items',
                                'The number of Items per Batch Request',
                                '100', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.auditlimit.solution.save.to.db', 'boolean',
                                'Save Capacity Usage to DB',
                                'By enabling this property, daily transaction count and storage usage will be saved in DB.',
                                'false', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.auditlimit.enable.checking', 'boolean',
                                'Checking Subplan Capacity',
                                'By enabling this property, data server will reject posted transaction if capacity usage hit limit of subplan.',
                                'false', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.dataServer.blockchain.enable.async.post', 'boolean',
                                'Async Transaction to BlochChain',
                                'By enabling this property, data server will asynchronized post transaction to BlockChain service.',
                                'false', true) ON CONFLICT DO NOTHING;
INSERT INTO TCTA_PROPERTY VALUES ('tcta.webServer.limit.history.cleanup.interval.inDays', 'integer',
                                'History clean up interval',
                                'The number of days to clean up limit exceed history',
                                '30', true) ON CONFLICT DO NOTHING;

-- initialized data for TCTA_UI_COLUMN
INSERT INTO TCTA_UI_COLUMN VALUES ('service_name', true, true, true, 'Business Process') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('user_trans_id', true, true, true, 'Transaction ID') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_state', true, true, true, 'Audit Event') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_status', true, true, true, 'Status') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_source', true, true, true, 'Source') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_destination', true, true, true, 'Destination') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_ts', true, true, true, 'Time') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('trans_desp', false, false, false, 'Description') ON CONFLICT DO NOTHING;
INSERT INTO TCTA_UI_COLUMN VALUES ('extra_props', false, false, false, 'Extra Information') ON CONFLICT DO NOTHING;

-- initialized blockchain service credential
INSERT INTO TCTA_KEY_STORE(CRED_ID, CRED_PW, CRED_CONTENT)
VALUES ('tcta.blockchain.client.key.prod', 'X/JhxbIWpeWO0f3XIIv+HQ==',
'OTYgpLTJx6+6QVG8QYTo4eGx6790vwzcYTXKswVmsgCz4K3qtaMz/A5jHW/ARHaOOGsyOC18RPgx+JrCrAWxujo82kn4PVdj916LSH5YFbCXIzuJS3qQyK8DFY/aIqpAqWW80h1CpYzjWgRng0N9YbLIkE7hU0isrRIW/AbTd+RcvXExipAip1lHSRgQ9e/TCpsFLiCkG66l14oAGmqyW/8PnVIbbxMEtnr+rzn0L4owg/BhaiEV1MUzal4hug77EW3tfoj8BTwEmlahXDtp7xkGo9XcT1AYBNRcNO5k7yvYHDsdORyHZxKLUSH2XBNGdBGl5C8wj7f3VuhuZbFkvMqwkmqoa3U9baRH8JhOiz4m7CGxO2ajgqeZxNpCSePlDzM/7ntNJsF/B/pBGDMOlx2zhKHsLAVpmNCgh97x6ztlW2zfcKNlRfxqoE1azewFOpJSf4UcqFjidZrWf9beP83hnkDqjtMuZV8j2HIN6Tty1fT5SIiBQ8teefCmwoj0jRJHHe5O/A6S85bETW57chq4xIUGmQZVtV+ZcH+jjFfb6LJ+vWENPCjLi36H97JvXMhRAOU5GHR+0t7T/AId1IUNY7AbsZXJgifM0MjaIKHngpImSVXSsXE+i/co72Uh15wM9hCoOwEJFWI0bH4+Nckm7LI2d+2Uupmo/mWl8edzm4Sn1LBrAuKavj3jC8yDT+QVpwq1x9J/4Jz1nBfa8AvDi0a2oNq2guF8oHwjXijvNvUEeBRGdIXYCIm/h33zik3eTIXoMuTiPc9ncCzLpeHZyoHGoFaN0HJmpnnXeaKyZEnn4oUerTTVZOwmOYchm0rtd8xtOJrgrHaNjBemQ5073ZAFsnDUFfZWfy9HyXnB0wJu3gmGlyURewPN1L1JGvfPNvwi4CpvkboPEzbggyMxuIzDyaSoBAVmDkd8hXm5nIR2RFTa1yjoGzh0SlnH8tO0ZuQvfR27X1n4a3ls1FyvupllU8my8z1746HgU/a9gIqv8rh/2zNb0azAzqcnUt3hcWJSpknPFT24h485jVvWPayoD//vXielJfI82T3bUHnXOlIXHqPLxrtIRKCOe1ec5AE3ijEzbhQqBcqFaL0r5SAKPTuanKkMuuXGeoPI5T4RAO7jT+yqSHZ2giRZfECuZFc0W7O8SV8TcG50ug6CXBQPl2FJ/ZsWrbE11H9KcFZG0/iXTEjCnopB6DlFYQ9HJN/qYBCdOuDWO4TwTSBoZm+mNpbFWGKyrcyFdIUqopMFJYWOpJrLZfJY68nGJEqOtjqd3mpd/6p0zTcntz49lC7wuyxtVreJ2Q8YjZtXnVdszFqGeSsQy8L/8CvKYYq5FdrxXIMH/qx6VRyKwRhw9n956dNa6ny9jGmUSiEupc3ll21F28FU+I5GDgiU0+v+4F3iVoPnPnCMR8ykBJRk86gL/2Rf91O/5l/rpfPkuguU1zT1MnjLM7ng5nPwZ9Oe3uKgH0IBf42lX9KDGlTNqmP4R2yPImNuByuQ8XdWmMH1mA/HnWUxJzMEkOLSHXxtfLPi2EJ8uJZWS3VJEavLyWEx8ffUsr4d8/xVnqEVDbIcCFInVidTDEeoxZamunEaEIgTBpuCN/aU209h65X5tMdgpt1tv0wJ+cRzegPAuFy2DtpM9K/oa5P1AOha59/UDEubdIFs+nXVFoW9ZjiTfWLAZvtv7ukcAM/z4KCTcp2Gd89p5ve32bphd57Iz8sylN+wZdKvOFEzdhsXTSOvzHR4jsz8BZjpn7clJVDHINhWmQPlOi5RMHupBG/zgTIVVmwiesgmxFcuAAb/Lr623fGzwrqw0t/WQih5xExNqSosHRsal2Cevu9QhVqRTGVBUYjTN+7e/1yotGLFQTSdevo4TE8GF/pwcy+Il/b3mM+F+Hu+6g+MB4+MiRtcJZA3F6mOm/vr9iveXet8sMztKoiivDVSNN0gp6D49MaPg1mfaQkHfbYyksM42XWrzHLohNivy3PU5TcYAr6qdPnu3DtYbtKwWJ/zt6D1XippkoWjGaPqwg7d+NPKesI0i4vxbNLbOlq8ZcIFEd/EmbZG+OxosKNoMWuMc8pNfr7csrRbRziDuJSyfNygm3N4565nnL0hWhTeTKtOxgGMEYHJ8ehUcAUAQ0Lm+H5oo0xwvJzI2NsXiJYUt3XIejHFU05MKU+61Qzi6GEaRUfHTfcqq3zhqrSm/F580A3dPraVQnr1iUtX8ws5reyJqRSx7yRS+OOGRh87UK96jvin9eUpeZopiQfFmDU2jlzOcShQqN+al27v/NXCijaOOyLdgg/ynSQTKxBGMIVhvjKnt2rYxuDX4N1VyJxlr5G9dv3/QR5i6WwA2Vkj+/mG13WcK2lX3+kzu4OoYLOTqonj85XYGQ31fXmATlKDaOE83jDm+oHyBKwX/CIH007VJx5GMa8ykDLCou0LtIyNX2MTUlJRxn2gTS0CaH+Rfsb9PAKcccaBY74Z6jGFKbW7R0LsVfWCjt7GM7aulScg4A8e67CEMNKxk+3grrC2/qHC3Uay/iDj/nOQqol07kT4YXd9Ck3sSHTYrYcJ2DJu5ks4gkkiIV47t+8Wk8Q3p7QcmtC1PZsz/i6xMszQg0KFbJO+QHltU2ZnSfSC1flNRoHov7EFYemqaOcZRidF+IfpfrQigo0FEa9aZXE5LJjXXvk+vgBq/gEwNJlwaEiB0AjBM/dSM1W03o+ucU0EJW4wu5yADY7h2ZZn+euxY+nRQcZ+I5wEqIzNKfX9U4DINT6bqiyYSO+FQCAIGivdS8k3vNO0tqEwFoV45fx75pYei76UyzeNKMYz+U9NsYekFRNDKtwJvx52LzScE2Xhf5anN9DqnRmYSyx8Aac0+W9psFyQSDr5rwCmLZ32WlYubotmZTDdaaVi1tNEcpMwydKa08t0ucaQGKYSYWkHJNtRSWbtKUPRyvasU8iWZaSVCP+yeyw08/M2Q5dqZYbeFoZ9IK3GpsH/UjftP0b7EnogkQbM94cJqXw4DcDxQd9n7GJfM8f1zOMeWuRkKtVQzSNAD/T1vX/ml0BuJicjETnoFih+nfsk5da6N7+quplQ5cIZtGXw0X30NMCe9xEIJOgbI2huZfXu8dfIQt2drOiM59Dp1xrj6fwaakvTva/LgYgtO2fvra8ljj0+YbRjbNXVIfQ3cEC6KdKKSRr/Nm+OHRctUiFcrBoD03XXL2zEp4U+VJrP8AyJkc86FNcUA0wpSn7bSI11daWMDM2E2S+67uoz3oiTgDzV3ULj6tfC+uUWX4rmfaZO+Q2FVTFY5SfDyt4P5Vg5wfOUvXlWSHbfLrAbhMhnFxrCM06MfhVCE0BZliykCtsaMrgTw88ELruOK7q0o1v3gGs+o7ZgRbkSHabUmRvS5iltkA2bOwbdY4Y1z75rupbhLA85AgFAfJ9NvXzelKS5w53tiSlgWk02nERII7ld5vTE5jDskftEJ1ydyg0EQ+f/njVyXq3m+LPokt++Y1SlxPbQYjrJ3uXTxpvL2TLmBv2Fgo62/C/1e7KhkTIFLMlxEd+tDhBTKXL/LXd6gd47ZWc+URNjs/SXqmBrawbw5wfOYXWzoNvpwVjIPsZrG6J5bwZDAg5vyjaxdZrntK+Eo53uWDpT+GAE0fHpVgM8Jte1/NIoRqnSckjVs6Wr63FMNCyqI1jfiKbNjKlRSWFwaMErTxqow57ocbc5z91CGyVXlJ1FWM84CI6E2OmujCFvu1wHRPpcHTKpdPVbvphQABX3s96vJ1OmHOf1ytoalNMd3vg8pkuwroYMXFgJoubTktarxjxSEACpSSnZgxx0iqPLEsNFvRChWj17pSydGwJUe7+Xyir36H9XZa1ncYqz7U7IkL9w2xBC2lj1op5/zODoouWp3cTSAyv5TeNx34giFkBi5RLltF71Ygtx3RwWi3dylii32PQCgLz6+5eB8dOLr9AldvhVrb8iwaXc5qUWesWzsO+/A0HP+aIDOGB1WdtCbCdZtFIBTOo=');
INSERT INTO TCTA_KEY_STORE(CRED_ID, CRED_PW, CRED_CONTENT)
VALUES ('tcta.blockchain.server.cert.prod', null,
'3457/4ezryIoIuIWmbsV+o4Bf45fzMOIzlF01zJv6Pi4rTl05h0zfc+l/TIzMZ4cttrpRoATm7uYH4ibhb0SrYiLW3J6nFTYUo8XmVjZFZOAECemg1TR/dbKl9ZnP7vtFNsI2g22BxydvKAhA1L9GgxGESODMB/+dBnOSiw+zwZxvF9PF093i/KmtsNZk47JWbGP11Ok4hBLSgKvdP3woCgzIFmOgb5XKPpYGsRMJG+vyqzqNHTJ7p/kY5iXmPWLUn2njk2hPkXyt3x/EX5eKhliS+8hl91+xgFxwKUV6Fdzlp3XIOtKVUNib/m7h/w6UO5LGc7CbGSAWw7IVZ053HVhsWBsebryuM9hLhFP8Gk0R50uunNYEWCRbsScyHp9uwpNehDkQgShyxvJSb18iGAVX7oPnvpwNE/7QTwkzcOhFaL+yCjXMu00miqenKKiXY5Ky4slaQbSlQihSlgoQyfHqWrFVjPp42bgtlzXRzERVxNGt1/9M/LzX3bg21TJ2lbGkTVGHXvOT9was+vM30SPlwZgOD2nfTz6EX03Fc5dp6jVOAYNPKDk/qw9F/GU/qBnXBXSbB3pIgsDgJUjRcz4A52QsqiSfECAxZthQ0KhGuMt1QUONj4pPzsP6KvUxrJc13shNq3cb+5GieXlLcpQx61pGhiFohiNK0NGh9HvGouEgV+ol5knYxvRZsigG+lEmc4mNtRdyixM2ft4BolLAASswbidMbJryV+qLVs2/fx22oa/Wj5VqSx4KyyaicmaO4nPwOxtN1CKEljsbe0SP3oLc3OvifUUzo3MT2os4/27GpjYLLeNTVr/ER76DsVFDSX4A9q/cbaGJu3iE6q48WsXTk4DQ5daLimhLyoM9CyCAhQGzZIVOSMh9drkUqU+F4I39w++MfrfuTuZlbOfrL5PAYVxDmi3V292ochHbjzuh1wsZY8QXBvTQa5UfjMTRpBSZSC+0Bu0aER9T2nF/4mS4WuuJlYXw/IdmyTbogSljdmUbnIOFXK+1OsoSN0QG0f/6Wg2864bdh21Pno6WCrubEcNKwxFWiE8lMlj8XS0aPMVtkQSKkzls5x8HUuIo68H+U+07aFfe+HH+rcbPnVB0xaKxnfL6fFOioZnJVAvX5kOj08pophUqf4s5Cf+nt88dqU7nxzFFYRoOB8n2KZOwAXnkYDdbkqdnFL1W3SFYUsPLtTgLUJfChnUN0atC+bfLR+mATY5GkHlkzVB+d+JSH08FySEwAKDmykBiyE06zkJXfwgJqmam3St7nY1mJLWDwXwl5dvA6y/7NtysGb5diRnUxmzcAUClTTpvw3eC0YJYalAQc2MTedlmUcG9j5oXdkws0LrH+4bfRbVCWT+z2blwJtBIoMMyxJmiLoLlhMeMveyNbO8DhRGWPZicyg0Pw60ZAhPgqQ2p6m5JhSJO9H0JTbWMlVXRVPtiP0UimattpZ1DxE7yrYYPr7kUdhf6o9y2/eS8b9IyWARi5z+oo4VLyFwqM/hnHNq1hV03k/ULXKyFkwH9MYWRnm3I8iWybs5C9mGEbGoBD17+S6euhyRZgizgwnKm6nkDVwn4kNKkLkIGV58XFaDwbsa1HDobwUt+ouRgDalkHYds9dAcKI7/ydj3thE66Y3Kl+QOk/f9BpFMwO4FJmM5xexGfNK5JT7vcTL6nIBK1m7nBGu1NFwZ2s0maWItzOyfxLCfQOfW4L9CV55xSZxY5hoDHXY7bGvieq9GD8eJZ8AVFylTa/ajB+um/wg4JhSd1cqZEIPOvnchR2OSbcgiK9F+lr5d3+1wejXF0kPwD6A17kMi++oB06XL4pB98AIoqxji2yMcWwAZaWcwxwEjsYknsuFGI9+ks+237H7JQoeB0NyCLR7ytOqHj/yY0YtZ+Q3bTN5h9444HRuJD6WvUMJMqg/WDXrzi25yLbd7aKNmBgTMylbi/e/m70i5720ZU9bVqwIXdJPQsbyBvAxtJqNF/BtrT3yiwTZ1GLc6Ec/TlBJdgKjxxQZCASKr0E=');
INSERT INTO TCTA_KEY_STORE(CRED_ID, CRED_PW, CRED_CONTENT)
VALUES ('tcta.blockchain.client.key.stage', 'X/JhxbIWpeWO0f3XIIv+HQ==',
'pMYSqWFFdLYFKcedH2FZWUf1S34xPoTlPggApgtMHLQEE6uduo7x6cqXPj18ZzOV2NpoFaihm0QYz7xKbB0pdA8rsypuZGQy41qjJbXwm04xThZPID7jT5BNmDvjRgE5k0jLzSnZ0FYJ5pvCG2ShgMgvsnrMrFoYvD8tt2zSEx7/obm2r/jZVi7Nb3u+kJGheLrH3FTW1f06Vm19v+ZFHePdYvNdVpIn5M4gC0LjFLrqUezFG7U9O7gwHb2/aKLlxoRXqM/gqC/2X7GSdLABM8xYcWMYEQF7/Kyw3oMHwra7ULk0L5nX6yUDo0AK/hvJzCIJqNAcKQuETW4dfThPd6XAukhaWClSbifvN7wt9nwsTsWjckxEJNJoGsiCs4La7VP0JBihYHXzyqUyr1jCOgmcY+C4R8Q9kBcCgbzCf6TGaUB4ZrMvxjFUfKCfRltFESJpzu2kIT3U8zeBrWu49AnLaAjSjWDj7doTs6gc8ZJpxFLtBI25clqtIM0PGwxuiDN/F/afMlsfRv99hSCWqryedWmdfy0M49g5qmVh0zrVFzl3iJa3hXZsKrNvPwyRIL+nd6MU2Gzj+GkbxIkASnKpv+Hl8ys91lmMwpfWzrjw2QWQI7a4Mf6g4CK/TM4UHDnycXcXMBTTt4cuWD+CpQyW9OsgElEK3a8qd8vmIcbvxVBupe4aQOvCWTKf6DGpomz/DZHWx/qkOJYMVOgBcgEv118E27zz01eyQUtAG37JujgTjyZbt/DUjXTRRoU4+qFKewHO7iM+CpZyo6DcDxjylW70FvHgdUp9Aw+Cn1iUPs8kDMgQo9i44vqgnUcVxTxaI22w40koSlCdPS9DTt5IYtyVA2sVjtyWt1LQZiMAKXrc5QSWRslsO4cHvws91HbIVXREDpb+x77wwVmFER8Nvs/FaeVuxOYqMHSoP3dW9EI1Xen9EA/8BNfhE+digEOb5vE/5uPdyBDQoBD4zqkHItoYCm4ME1c9UzQxT7OcGYzl9lGLuBpz2Ii6okZPzKpCThtyG3OL9lX/jAj1KlQ6IDxb71UYD5lzDB68K4ShHy9sYiMa1Qc3XW8Sv1PNdjl3s0MGiC3Afu0o29NeZzLkeITFCjHNQ305iw4O4N/yJbaoZYzs7CvVMvrxFpxrBxd37MSSHeUZjfkR1ePro/zh+YEFgV5jjq6HtYfFXkGrveYT45H6cLvTVva2Q9RfpVCF1MWAdMJvH6D8O4ZxTO23xI/dZQXelYy/MRnYC8i0D+hwVctP3QOpxmGUrIoCib1+FvYgqEIpXvBm84kOjDOyxxcgMqdIlQQm5V0L7xYXymKz5nYWAyJKJbxkm7Pfg/oTXiRGTXCRuEe/2UTgbRvk2r2IQKOsEZIaTGJty53oOsnRJqWAfbnhCaZiZsoyqBlGqm0JDLd92JrjzsGng/e6wcjK8IAy9kqhoBqOh9jh7lmR00nwQpUwvKDt97xAXj8JOatrDFncOb+CuuoHYJkSG2rWXTrGi5ClVH5RVDWN2Peqy7unqxqsK3GUpdXWSHx/YScAkAjFeKg63mSOLNXQNHwkP83DHrxMOSE2cQf6bV5x3ad7UTBUiQ7+z4BDeJS2UURGvW9DhktPp2QYKcJkhT2N1ES8YoFObYHv3MECnzfquf8k6djf9NlZC6q01001mzaKUK/mEK2BMAYP8m2MHnOMMsRqQVCOviN42YsboTRlM0N83uKrxP3zLa6DqRwWhk1eNkqvFjhiVLAEb2GlmlLMv/efr+2NxzdXl7pfen0zb0a4g95ihnayq3J8leopp9KTT9Y8B9ws3Bz4UIDtMbdEGHmXnwtrSJ0UQOljRZGRywIIlPsZFm7Dj8btwCytR20/2VLy1Jo9oV/ePsL1WyL6hA8Tkfqmrz4tZoOXQZcCTUzmePkfbBUXe+GAeZQ9UnSfC4MY+f8ML2FBhpccZajQn3xmMucdBlPisG7ea0ovBwUcQU7HGMsjgRecnAJHu/8HSgJyqZhy5DGpO9PBdZRf++vz6eWPl/9s5ScM1X4ulVDlw0G3LUVsTplCxwPohle3BM+XEDE5Ulpo2FVWRRWTzCgt+HNvEs2+63TIXB897U4nvzXOb2IJasWwDxaP2xViXNu0k1XcjvzZSmmqTeV9thCcxIuQUZYkhEAGVlQvMW3Wogb0czwvV5J+ong17p1s808h33baXi1gIZ/dddcLWNxIZ5JrepC0QyEwwwnLyAYGjXVQSzsnoccRVV/D8adECuYE7tapLd1ykvsOh0smrwB+YGMF389ycmqHSp0St9FfslIDIQH1+bHZX9aDV6mDCzCBW7ijfKtNzUYMbWU/in4dXEA/VQxU6tHxRG2tpVyE4+vjjkM6CnaAG+QmOUPlQVpr2CJbOHbsJ6g3CkzKN4xli7wLo3MntttQARO1dkz+r4/jIP2xloSwN13o0ncYfQP1Whcy2gxFeqvbiJW2aSpScSpjp2Lsi9Vrg9sygo9ePRbYl25lNmZxQjNlg/Fw9twxwXenjSjKlxVok5YOFsu0cqMG6HMk/o4B5dzDKw2UhBxyB+0dD8vzNlWhRQH0V9yfzBgnJ5/+xX2j8ri/GOUBhJhiFbtrMU/+dMiII3TSm5rHXdvhH9/D2csNVYXYzQOr5A0sPQ7sOtaivxHsCbjLPKSgUKlHigk3+PGQWkMa8B7fZpCRHBr2Ys7u+LLM13ytksyiRdPxREK503KLv/oTUL6cwwl4nEs2yylFkwGPW7B5YJ51/giZfo0gyw0VARtqis+onKOVnpSpos8tzi6gw4A/xL9a6+4lJgIBD4BMIscBXBT2WrQMdaklolqFqz0r3zzO5h+6dwIsLIQCiCNnnILr2nbVtTacbyarRT0lfg23VsuIYNBA2Zs8HKvwUnXTpremh/lQBXj54t79m6R9BoI92eUG5yTajDYOD7mANXGEUmGoGmPag/E0sYvmql+H9ohpcDVZB40sVuOFoUpGggnhouWB+LjSefY0Sgvib47ZdmYPZ5TyY7EtpZgFwoGhWymm+E8M6SH83tlRRPs58luF0CkRKlbL1nftBQru7UGUKYYUowF6pkRF1zv6mvSqweAKcDAGG49zXpmVG/9e2VLV0U+fo1K0rLCJUqMu1IaqmRGV3i+BecSfUc8Su+Xfrqro/3VViH3mJoVS9eIX3kJ9ZkAnvgET1I8hVRpOxM/iqWWpbZ2jJW56nbxjADpt/CrxOyJDChuC7UPc5xgZ0ekXLARAlFnigCHh58QPOkhuWlw8kCSCLdoxqA+02LyYJwvtc4F5NFshwiOul82ZvgXGCwYGsFjQQEv6DshDIGGwICa5ZmWXMkIJyLXvbCDRlwLT07HyXo1YOPu3kabfbKc3QEcXU0Ox/kCeNPkU9r82W0r3ExtOS5F3MeEx//kN5eZE7hcXkoltf5Bo8RhNiUnrvzWLath1mrPbrsAAFuxdh8Wbb0Qbkj5PCw4cjBnWJfOk7SkcjZc+1IilsHFhnzTK5bzNmgMDpfW6ztXcJIqcZqnJBacz/V5tHSWc/rqWN8ZcElrts2T/IhjvXuAMoWda2K+FgibVSPaVpLYUR/b6UyKKKP61VJIP5KLq+XoElzTBtmKzxRjqxhGXkh0rZQE8bJEagNPuGO5SQNXCu4JhQ8ERMNemf0LLRq/4SYjrjVREWY8oiMVAnHfjcUNaJk8bIbGHlvM739k0kdUSQdJpWQrhHI6jrlNGDQJ0T5GHDs6zu5C8eE0WbvhGGTVUyz0nDXKENm8Mp4hdrN3xUGuNmQe4CRl1iULeOZU/Y6wwok0fMGqXNpCm8A+Q2U1B+9Lo1znPEg2dT+o66Qnd20i8j0iV6GcpoXW4lAkCiuRaxo6l3pDlmq9sWcen45vruS45p3hE6KXjMtj/T2R0J5zd//uoeQcAxmcJGoPxVGrUVwM7b/jnsvgHdxZ/kxNvO6MVZ3BHedGMmOzZ2cmquBurh3JWX/yKilSDwaauvQYakgyyWh00rTuBvFm3H1S/zBzJR/Io1N0=');
INSERT INTO TCTA_KEY_STORE(CRED_ID, CRED_PW, CRED_CONTENT)
VALUES ('tcta.blockchain.server.cert.stage', null,
'I5OFIK7U24IKjjyIrdQTlmNcjwmDc9q23DgrSEN1Bh92mAnQpELycGt4Df/HFW6udrVP+evd03dovbDdamdttWxS/c1uCVElMucC9N9OBX9W5qQKZpwQVtQh+e7MofDONbWeK6PlZL9GJHdtP2KzyMFBs1ToOvRDPVod3IyfOyx//mBA2H0IsF0xHFLfAEHVEdc+y8jNLVuCIfGovOOSdV/y/rR/VDTdcpX2NCdDJJtcGPLy5kBRuJzwkHwx54WyL0g5myuGdqQmbIgzLu/ZGk/JaRfgT222pcwbkUiWgUQTxdXjSgiPDO57EPO6E5/0VAdJD6jWqKiIxWNoDghOGq4ARfS/D3j6avnYJ4xvpuea+mB67BnM7no1ZgnjY4K4rTzkn1Ph9FH+H2LzM9gPXROY+xiT/Kynjy2T6tfuoYFBY5heFrE/aR5CGpPAreNoR79pqfQB3GnGE80aQA/kd/KRSkbkIxYESicaOUnmS45kZhWQncdgJBSeb6zTmJnGrO2Wn8kVmwLeJUO4ONxvMxCby6dLJ/+o8uSZwJa0+riI4i6mWUM853kneQQVLC9+DBxWw5E3DMSILjKpuyP1WDmECcBbB2W5SkamU1a58SH4V56qEzj1cG7hVull+RUBpdN5n8xQc5NYioyGonXUoDYOGp7fDwJ7eNRyZOWYm/662GW/p6pwgNljXnuYJ2e4KJXbbofOjSsNGgrFyj/7CyclLjaJYY7yGxkh5bZW0ASCQICXuwqTp6I58DZ68cuv/x/fE/3xya6sCZQKnINca7NJSdv8Z7cDQIgJJ55QXSfL9rrYLD9X33qY5XFWlFYJESFjNuGNT9sXvXDkxOhs8As1Yx898WylkS4ijEbT/xjpRLDeO3JlyoABnpTejZwmy82KPbiOMyYkcqW+YWf0pBGu81GAaED53cnymj49owGTKfNrXvRFT+9siwp/BOxVynqvCjRZfbRQZD6wKmk2pQFlzR/xC3M1hhFLdrBOjOwfOoT7O7odnp77hJS8T2Gx2vTkWMRngrpOyA+o5VuzVO13C15fn50R61euHizv4plw8ucW2Hs6mVqPke2AZMSCzjvprzBN51+6Say0MgNPLTI4HKdhMbwXVZfOwDbBPSQPQ0W10sJw+D3IN0LFq9MGKhzEga9DI2gnjezdSgsFlYcXu9Rj+mZeySVb5GBeSI2hSINIPaSJu8ovHfivyr3YHWmwmIqdFGELjAtZcWWqxFFDEGNKk4l+MJZEtucXiOi7UCp72djh2nrOVj/aNFuQ9dYzTUULe6OQBlleIbUTePLsZI8KJzGnsc5iLqIvBAjJWY2AB2cw6lMa+bbxEhLT0aBCzTNKHF9qsB9PDcNx/wcZrm65CYDRx1uC4RdiU9tko9hn3lREAUsPD0BiQegGBHgIW5yDyhLqKs+JA9zXk8Y7QSzG1FWvomciaOQ8RiijbZukV1Gswe0OxkhkpAGU5HamcUsVjjTcGjbRXwehFi7lTdlFH07ZAd84As/q7+gEg5ksD0truVDlY88y/GbR5AtTJQtSE7XQiDht4q+oGaaoMc8EgFUlJTxppht6l4C2oUvmjgl6PWRPD7SIoPU8WvRUri0zxcFB4c4qrYxdolQxYHGfl/Pb9ES59gMlNSGoHjpbrYaeIDO67PKYbciM7D4PdolisgJHDF+AsC6ed/t9Q/2h4wgmPCcKmjeJuJ6/a0+53g0Mp0h+7MUzLxePbHGu3lk4GR6gEFkAct9oEoRQNFBBDM0w5ylQOm5kwB7nvne9d9INna9YR+RJzdap+ilDjGTrBnpvYa2BXXeMqZCUwX+s7JSamR/MXMfA1CWEnoQ5rmBgwBdA3/xt97l7EVLFOQazI3r9GhXfpaXuiIYMg1utsqtzol4/gbUP1pLzoVf+rLiTxeX6MvYn9chiIrMeftuSnhvf3x3YHGOejpLBEAtzTOuY/Lrw0dGiBawmSLQl0owwyE/701LandOKgB8HDU0er1g0In0rIR6zmu6eBRzk7HgS0OPOI4W8fEM=');



------------------------------------------------------------------
-- below is sample data init sql
------------------------------------------------------------------
-- create partition table for demo data
CREATE TABLE TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF PARTITION OF TCTA_TRANSACTION(
    CONSTRAINT TCTA_TRANSACTION_pkey_01CJSXXD5892QYJVR4R91384TF PRIMARY KEY (TRANS_ID)
) FOR VALUES IN ('01CJSXXD5892QYJVR4R91384TF');
--:
CREATE INDEX TCTA_TRANSACTION_IDX1_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_TS);
--:
CREATE INDEX TCTA_TRANSACTION_IDX2_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (USER_TRANS_ID);
--:
CREATE INDEX TCTA_TRANSACTION_IDX3_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_SOURCE);
--:
CREATE INDEX TCTA_TRANSACTION_IDX4_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_DESTINATION);
--:
CREATE INDEX TCTA_TRANSACTION_IDX5_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (SERVICE_NAME);
--:
CREATE INDEX TCTA_TRANSACTION_IDX6_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_STATUS);
--:
CREATE INDEX TCTA_TRANSACTION_IDX7_01CJSXXD5892QYJVR4R91384TF ON TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_STATE);
--:

-- create partition table for TCTA_TRANSACTION_PAYLOAD
CREATE TABLE TCTA_TRANSACTION_PAYLOAD_01CJSXXD5892QYJVR4R91384TF PARTITION OF TCTA_TRANSACTION_PAYLOAD(
    CONSTRAINT TCTA_TRANS_PAYLOAD_pkey_01CJSXXD5892QYJVR4R91384TF PRIMARY KEY (PAYLOAD_ID),
    CONSTRAINT TCTA_TRANS_PAYLOAD_fkey_01CJSXXD5892QYJVR4R91384TF FOREIGN KEY (PAYLOAD_ID)
    REFERENCES TCTA_TRANSACTION_01CJSXXD5892QYJVR4R91384TF (TRANS_ID)
) FOR VALUES IN ('01CJSXXD5892QYJVR4R91384TF');
--:

--State definitions for the user
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('PO RECEIPT', 'Purchase Order received', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('CREDIT CHECK', 'Credit Check is performed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('ORDER CREATION', 'Credit Check is passed, wholesale order is placed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('INVENTORY CHECK', 'Inventory check for the placed order', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('DO CREATION', 'Delivery Orders are created', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('SHIPMENT CREATION', 'Shipments are created', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATE (STATE_NAME, STATE_DESP, TSC_SUB_ID) values ('DELIVERY', 'Shipments are complete', '01CJSXXD5892QYJVR4R91384TF');

--Status definitions for the user
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('CREATED', 'PO received', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('OPENED', 'OPENED', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('IN PROGRESS', 'processing', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('SUCCESS', 'Transaction successfully Completed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('COMPLETED', 'Transaction Completed', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('FAILED', 'Transaction Rejected', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('PARTIALLY COMPLETE', 'Portion of the task is complete', '01CJSXXD5892QYJVR4R91384TF');
INSERT INTO TCTA_STATUS (STATUS_NAME, STATUS_DESP, TSC_SUB_ID) values ('PENDING', 'Transaction waiting on previous state to complete successfully', '01CJSXXD5892QYJVR4R91384TF');
