-- update schema_version table
UPDATE SCHEMA_VERSION SET VERSION = 4;

CREATE TABLE IF NOT EXISTS TCTA_COLUMN_CONFIGURATION(
	USER_ID        		 CHARACTER VARYING(128) NOT NULL,
    CONFIG_NAME          CHARACTER VARYING(128) NOT NULL,
    IS_DEMO			 	 BOOLEAN,
    GROUP_BY             CHARACTER VARYING(128) NOT NULL,
    COL_NAMES      	     CHARACTER VARYING(5000) NOT NULL,    
    GROUP_BY_USER_TRANS_ID BOOLEAN,
    CREATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (USER_ID, CONFIG_NAME, IS_DEMO)
);

CREATE TABLE IF NOT EXISTS TCTA_SUB_EMAIL(
	TSC_SUB_ID        	 CHARACTER VARYING(128) NOT NULL,
    EMAIL      		 	 CHARACTER VARYING(128),
    CREATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TSC_SUB_ID)
);

ALTER TABLE IF EXISTS TCTA_STATUS
ADD COLUMN IF NOT EXISTS is_error BOOLEAN,
ADD COLUMN IF NOT EXISTS is_complete BOOLEAN,
ADD COLUMN IF NOT EXISTS need_notify BOOLEAN,
ADD COLUMN IF NOT EXISTS email CHARACTER VARYING(128),
ADD COLUMN IF NOT EXISTS color CHARACTER VARYING(16);

CREATE TABLE IF NOT EXISTS TCTA_QUERY_HISTORY(
    QUERY_ID     UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    QUERY_NAME      CHARACTER VARYING(128) NOT NULL,
    QUERY_STRING        TEXT NOT NULL,
    USER_ID         CHARACTER VARYING(128) NOT NULL,
    TSC_SUB_ID      CHARACTER VARYING(128) NOT NULL,
    IS_DEMO			 	BOOLEAN,
    CREATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
