-- update schema_version table
UPDATE SCHEMA_VERSION SET VERSION = 4;

DROP TABLE IF EXISTS TCTA_RETENTION_PERIOD;
DROP TABLE IF EXISTS TCTA_PAYLOAD_CONTROL;
DROP TABLE IF EXISTS TCTA_ENCRYPTION_KEY;
