-- update schema_version table
UPDATE SCHEMA_VERSION SET VERSION = 5;

CREATE TABLE IF NOT EXISTS TCTA_RETENTION_PERIOD(
	TSC_SUB_ID        	 CHARACTER VARYING(128) NOT NULL,
    MONTH      		 	 SMALLINT,
    MAX_MONTH 			 SMALLINT,
    CREATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TSC_SUB_ID)
);

CREATE TABLE IF NOT EXISTS TCTA_PAYLOAD_CONTROL(
	TSC_SUB_ID        	 CHARACTER VARYING(128) NOT NULL,
    VISIBLE      		 BOOLEAN,
    ENCRYPT 			 BOOLEAN,
    KEY_ID			     CHARACTER VARYING(256),
    KEY_NAME			 CHARACTER VARYING(128),
    KEY_CONTENT			 CHARACTER VARYING(2000),
    CREATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY (TSC_SUB_ID)
);

CREATE TABLE IF NOT EXISTS TCTA_ENCRYPTION_KEY(
	KEY_ID				 UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	TSC_SUB_ID        	 CHARACTER VARYING(128) NOT NULL,
	DISABLED			 BOOLEAN NOT NULL DEFAULT TRUE,
    KEY_NAME			 CHARACTER VARYING(128),
    KEY_CONTENT			 CHARACTER VARYING(2000),
    KEY_HASH			 CHARACTER VARYING(128),
    CREATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
