-- update schema_version table
UPDATE SCHEMA_VERSION SET VERSION = 5;

-- delete properties (only if they exist)
DELETE FROM TCTA_PROPERTY WHERE prop_key='tcta.webServer.download.file.maxTransactions';
DELETE FROM TCTA_PROPERTY WHERE prop_key='tcta.dataServer.enable.events.resending';

ALTER TABLE IF EXISTS TCTA_STATUS
ADD COLUMN IF NOT EXISTS email CHARACTER VARYING(128),
DROP COLUMN IF EXISTS BUSINESS_PROCESS,
DROP COLUMN IF EXISTS GROUP_NAME;

DROP INDEX IF EXISTS UNQ_STATUSNAME_BUS_SUBID;
CREATE UNIQUE INDEX IF NOT EXISTS UNQ_STATUSNAME_SUBID ON TCTA_STATUS (lower(STATUS_NAME), TSC_SUB_ID);

DROP INDEX IF EXISTS UNQ_GROUPNAME_SUBID;
DROP TABLE IF EXISTS TCTA_SUB_EMAIL;

CREATE TABLE IF NOT EXISTS TCTA_SUB_EMAIL(
	TSC_SUB_ID        	 CHARACTER VARYING(128) NOT NULL,
    EMAIL      		 	 CHARACTER VARYING(128),
    CREATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (TSC_SUB_ID)
);

DROP TABLE IF EXISTS TCTA_RESEND_EVENTS;
