-- UPDATE SCHEMA_VERSION SET VERSION = 7;

CREATE TABLE IF NOT EXISTS DASHBOARD_PROFILE (
    DASHBOARD_ID   UUID NOT NULL DEFAULT uuid_generate_v4(),
    DASHBOARD_NAME CHARACTER VARYING(128) NOT NULL,
    SUB_ID         CHARACTER VARYING(128) NOT NULL,
    USER_ID        CHARACTER VARYING(128) NOT NULL,
    TAGS           CHARACTER VARYING(128),
    TEAM           CHARACTER VARYING(128),
    DATAPLANE_ID   CHARACTER VARYING(128),
    ORIGIN         CHARACTER VARYING(128) NOT NULL,
    PROFILE        JSONB,
    CREATE_TS      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UPDATE_TS      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    EXPIRY_TS      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (DASHBOARD_ID)
);

ALTER TABLE DASHBOARD_PROFILE
  DROP CONSTRAINT IF EXISTS dashboard_profile_unique_name_sub_user;

ALTER TABLE DASHBOARD_PROFILE
  ADD CONSTRAINT dashboard_profile_unique_name_sub_user
  UNIQUE (dashboard_name, sub_id, user_id);

UPDATE SCHEMA_VERSION SET VERSION = 7;
