-----------------------------------------------------------------------------
-- SQL statements for deleting all tables created for TCTA DataServer
-----------------------------------------------------------------------------

-- NOTE: Please keep on adding DROP TABLE SQL query if any new table is been added.

DROP TABLE IF EXISTS TCTA_TRANSACTION_PAYLOAD;
DROP TABLE IF EXISTS TCTA_TRANSACTION;

DROP TABLE IF EXISTS SCHEMA_VERSION;
DROP TABLE IF EXISTS TCTA_AUDIT_LIMIT;
DROP TABLE IF EXISTS TCTA_SEARCH_HISTORY;
DROP TABLE IF EXISTS TCTA_UI_COLUMN;
DROP TABLE IF EXISTS TCTA_COLUMN_VISIBILITY;
DROP TABLE IF EXISTS TCTA_SETTING;
DROP TABLE IF EXISTS TCTA_PROPERTY;
DROP TABLE IF EXISTS TCTA_STATE;
DROP TABLE IF EXISTS TCTA_STATUS;
DROP TABLE IF EXISTS TCTA_KEY_STORE;
DROP TABLE IF EXISTS TCTA_BC_POLLER_INFO;
DROP TABLE IF EXISTS TCTA_BC_POLLER_LOCK;
DROP TABLE IF EXISTS TCTA_CAPACITY_USAGE_HISTORY;
DROP TABLE IF EXISTS TCTA_HISTORY_LOCK;
DROP TABLE IF EXISTS TCTA_COLUMN_CONFIGURATION;
DROP TABLE IF EXISTS TCTA_SUB_EMAIL;
DROP TABLE IF EXISTS TCTA_QUERY_HISTORY;

DROP TABLE IF EXISTS TCTA_RETENTION_PERIOD;
DROP TABLE IF EXISTS TCTA_PAYLOAD_CONTROL;
DROP TABLE IF EXISTS TCTA_ENCRYPTION_KEY;

DROP FUNCTION IF EXISTS UPDATE_TIMESTAMP_FOR_CHANGE();
