
----------------------------------------------------
-- Database (tscorchdb) schema based on tsc 2.51.0
----------------------------------------------------

--
-- Name: TENANT_SUBSCRIPTION_LOCKS
--

CREATE TABLE IF NOT EXISTS TENANT_SUBSCRIPTION_LOCKS (
	SUBSCRIPTION_ID VARCHAR(255) NOT NULL,
	TENANT_ID VARCHAR(255) NOT NULL,
	REGION VARCHAR(255) NOT NULL,
	
	CONSTRAINT TENANT_SUBSCRIPTION_LOCKS_PKEY PRIMARY KEY (SUBSCRIPTION_ID, TENANT_ID, REGION)
);

--
-- Name: SCHEMA_VERSION
--

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
    ID SERIAL PRIMARY KEY,
    VERSION INTEGER NOT NULL,
    
    CONSTRAINT UNIQUE_CONSTRAINT UNIQUE (VERSION)
);

INSERT INTO SCHEMA_VERSION (VERSION) VALUES (1) ON CONFLICT DO NOTHING;