{{/*
Copyright © 2023. Cloud Software Group, Inc.
This file is subject to the license terms contained
in the license file that is distributed with this file.
*/}}

{{/*
    NOTES: 
      - This file will be generated by the build server. DO NOT EDIT!
*/}}

{{/* The build number, also used as docker image image tag */}}
{{- define "tibco-developer-hub.generated.buildNumber" }}latest{{ end -}}