
---------------------------------------------------------
-- Database (tscschedulerdb) schema based on tsc 2.51.0
---------------------------------------------------------

--
-- 1. Name: CC_PAYMENT_ISSUES
--

CREATE TABLE IF NOT EXISTS CC_PAYMENT_ISSUES (
	TSC_ACCOUNT_ID VARCHAR(255) NOT NULL,
	TSC_SUBSCRIPTION_ID VARCHAR(255) NOT NULL,
	REGION VARCHAR(255) NOT NULL,
	START_TIME BIGINT NOT NULL,
	LAST_UPDATED_TIME BIGINT NOT NULL,
	
	CONSTRAINT CC_PAYMENT_ISSUES_PKEY PRIMARY KEY (TSC_ACCOUNT_ID, TSC_SUBSCRIPTION_ID, REGION)
);

--
-- 2. Name: START_JOB
--

CREATE TABLE IF NOT EXISTS START_JOB (
	JOB_NAME VARCHAR(255) NOT NULL,
	REGION VARCHAR(255) NOT NULL,
	START BOOLEAN NOT NULL,
	
	CONSTRAINT START_JOB_PKEY PRIMARY KEY (JOB_NAME, REGION)
);

--
-- 3 Name: SCHEMA_VERSION
--

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
	ID SERIAL PRIMARY KEY, 
	VERSION INTEGER NOT NULL,
	
	CONSTRAINT UNIQUE_CONSTRAINT UNIQUE (VERSION)
);

INSERT INTO SCHEMA_VERSION (VERSION) VALUES (1) ON CONFLICT DO NOTHING;